<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="5" id="0" name="" package="" skipped="0" tests="5" time="20.770">
    <testcase classname="" name=".setUpClass (serial_scripts.k8s_auth.test_policy_combo.TestPolicyCombo)" time="0.000">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/serial_scripts/k8s_auth/test_policy_combo.py&quot;, line 22, in setUpClass
    super(TestPolicyCombo, cls).setUpClass()
  File &quot;/contrail-test/serial_scripts/k8s_auth/base.py&quot;, line 14, in setUpClass
    dstdir=&apos;/var/tmp/templates&apos;)
  File &quot;/contrail-test/common/contrail_test_init.py&quot;, line 1610, in copy_file_to_server
    host[&apos;username&apos;] = self.host_data[ip][&apos;username&apos;]
KeyError: &apos;192.168.7.18&apos;

</failure>

    </testcase>

    <testcase classname="" name=".setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResource)" time="0.000">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/serial_scripts/k8s_auth/test_resource.py&quot;, line 23, in setUpClass
    super(TestK8sResource, cls).setUpClass()
  File &quot;/contrail-test/serial_scripts/k8s_auth/base.py&quot;, line 14, in setUpClass
    dstdir=&apos;/var/tmp/templates&apos;)
  File &quot;/contrail-test/common/contrail_test_init.py&quot;, line 1610, in copy_file_to_server
    host[&apos;username&apos;] = self.host_data[ip][&apos;username&apos;]
KeyError: &apos;192.168.7.18&apos;

</failure>

    </testcase>

    <testcase classname="" name=".setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResourceCustom)" time="0.000">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/serial_scripts/k8s_auth/test_resource.py&quot;, line 74, in setUpClass
    super(TestK8sResourceCustom, cls).setUpClass()
  File &quot;/contrail-test/serial_scripts/k8s_auth/base.py&quot;, line 14, in setUpClass
    dstdir=&apos;/var/tmp/templates&apos;)
  File &quot;/contrail-test/common/contrail_test_init.py&quot;, line 1610, in copy_file_to_server
    host[&apos;username&apos;] = self.host_data[ip][&apos;username&apos;]
KeyError: &apos;192.168.7.18&apos;

</failure>

    </testcase>

    <testcase classname="" name=".setUpClass (serial_scripts.k8s_auth.test_restart.TestRestart)" time="0.000">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/serial_scripts/k8s_auth/test_restart.py&quot;, line 22, in setUpClass
    super(TestRestart, cls).setUpClass()
  File &quot;/contrail-test/serial_scripts/k8s_auth/base.py&quot;, line 14, in setUpClass
    dstdir=&apos;/var/tmp/templates&apos;)
  File &quot;/contrail-test/common/contrail_test_init.py&quot;, line 1610, in copy_file_to_server
    host[&apos;username&apos;] = self.host_data[ip][&apos;username&apos;]
KeyError: &apos;192.168.7.18&apos;

</failure>

    </testcase>

    <testcase classname="" name=".setUpClass (serial_scripts.k8s_auth.test_restart.TestRestartWithPodResource)" time="0.000">
      <failure type="testtools.testresult.real._StringException">Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File &quot;/contrail-test/serial_scripts/k8s_auth/test_restart.py&quot;, line 130, in setUpClass
    super(TestRestartWithPodResource, cls).setUpClass()
  File &quot;/contrail-test/serial_scripts/k8s_auth/base.py&quot;, line 14, in setUpClass
    dstdir=&apos;/var/tmp/templates&apos;)
  File &quot;/contrail-test/common/contrail_test_init.py&quot;, line 1610, in copy_file_to_server
    host[&apos;username&apos;] = self.host_data[ip][&apos;username&apos;]
KeyError: &apos;192.168.7.18&apos;

</failure>

    </testcase>

  </testsuite>
  <testsuite errors="0" failures="0" id="1" name="" package="" skipped="0" tests="0" time="3.675">
    <properties>
      <property name="LogsLocation" value="http://10.204.216.50/Docs/logs/2011-169_2021_02_18_05_42_54/logs/" />
      <property name="Build" value="2011-169" />
      <property name="Report" value="http://10.204.216.50/Docs/logs/2011-169_2021_02_18_05_42_54/junit-noframes.html" />
      <property name="Topology" value="&lt;br/&gt;DISTRO : &quot;Ubuntu 18.04.5 LTS&quot; &lt;br/&gt;SKU :  &lt;br/&gt;Config Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Control Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Compute Nodes : [&apos;noden19&apos;, &apos;nodec9&apos;] &lt;br/&gt;Openstack Node : [&apos;noden20&apos;, &apos;nodei34&apos;] &lt;br/&gt;WebUI Node : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Analytics Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Database Nodes : [&apos;noden20&apos;, &apos;noden29&apos;, &apos;nodei34&apos;] &lt;br/&gt;Physical Devices : [&apos;&apos;] &lt;br/&gt;" />
      <property name="cores" value="{&apos;192.168.7.20&apos;: [], &apos;192.168.7.29&apos;: [], &apos;192.168.7.34&apos;: [], &apos;192.168.7.19&apos;: [], &apos;192.168.7.9&apos;: []}" />
    </properties>
  </testsuite>
</testsuites>
