2021-02-22 05:02:52,015 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:02:52,046 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:02:52,416 - INFO - Project ctest-TestvDNSBasic0-10124299 not found, creating it
2021-02-22 05:02:53,020 - INFO - Created Project:ctest-TestvDNSBasic0-10124299, ID : a15ca110-41c7-43f5-aca4-a2c300864f84 
2021-02-22 05:02:56,594 - INFO - ================================================================================
2021-02-22 05:02:56,594 - INFO - STARTING TEST    : test_vdns_ping_same_vn
2021-02-22 05:02:56,594 - INFO - TEST DESCRIPTION : 
        Test:- Test vdns functionality. On VM launch agent should dynamically update dns records to dns agent
            1.  Create vDNS server
            2.  Create IPAM using above vDNS data
            3.  Create VN using above IPAM and launch 2 VM's within it
            4.  Ping between these 2 VM's using dns name
            5.  Try to delete vDNS server which has IPAM back-reference[Negative case]
            6.  Add CNAME VDNS record for vm1-test and verify we able to ping by alias name
        Pass criteria: Step 4,5 and 6 should pass

        Maintainer: cf-test@juniper.net
        
2021-02-22 05:02:57,937 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:02:57,937 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:02:57,937 - INFO - 
2021-02-22 05:02:59,386 - INFO - Using existing project ['admin_domain', 'ctest-TestvDNSBasic0-10124299'](a15ca110-41c7-43f5-aca4-a2c300864f84)
2021-02-22 05:02:59,454 - DEBUG - Creating VDNS : ctest-vdns1-81353168
2021-02-22 05:02:59,563 - DEBUG - VDNS: ['admin_domain', 'ctest-vdns1-81353168'] created succesfully
2021-02-22 05:02:59,563 - DEBUG - Verify VDNS entry is shown in control node
2021-02-22 05:02:59,564 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-81353168
2021-02-22 05:02:59,582 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-81353168
2021-02-22 05:02:59,681 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-81353168
2021-02-22 05:02:59,697 - DEBUG - Verify VDNS entry is shown in the API server
2021-02-22 05:02:59,698 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:03:00,924 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:03:01,116 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:03:01,169 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-DNS/a623024b-a0c4-4cff-8114-60ac9c616904
2021-02-22 05:03:03,836 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestvDNSBasic0-10124299', 'ctest-vn1-vdns-45513828'], 'name': 'ctest-vn1-vdns-45513828', 'admin_state_up': True, 'tenant_id': 'a15ca11041c743f5aca4a2c300864f84', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'a15ca11041c743f5aca4a2c300864f84', 'id': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66', 'description': ''}}
2021-02-22 05:03:05,240 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66', 'tenant_id': 'a15ca11041c743f5aca4a2c300864f84', 'created_at': '2021-02-22T05:03:04.417983', 'dns_nameservers': [], 'updated_at': '2021-02-22T05:03:04.417983', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '10.10.10.2', 'end': '10.10.10.254'}], 'gateway_ip': '10.10.10.1', 'dns_server_address': '10.10.10.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '10.10.10.0/24', 'id': 'b1dcc994-b979-45fb-8e75-8eacd9939071'}}
2021-02-22 05:03:05,379 - INFO - Created VN ctest-vn1-vdns-45513828
2021-02-22 05:03:05,415 - DEBUG - VN ctest-vn1-vdns-45513828 UUID is ea5c1fa6-ec6f-461e-a435-000f1725fd66
2021-02-22 05:03:05,949 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-22 05:04:37,419 - INFO - Deleting VN ctest-vn1-vdns-45513828 
2021-02-22 05:04:38,424 - DEBUG - Response for deleting network ()
2021-02-22 05:04:38,547 - DEBUG - Deleting VDNS Entry: ctest-vdns1-81353168
2021-02-22 05:04:38,669 - INFO - VDNS info: ['admin_domain', 'ctest-vdns1-81353168'] deleted successfully.
2021-02-22 05:04:38,670 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:04:38,692 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:04:38,731 - DEBUG - VDNS information not found in API server
2021-02-22 05:04:38,731 - INFO - VDNS information ctest-vdns1-81353168 removed from the API Server
2021-02-22 05:04:38,732 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-81353168
2021-02-22 05:04:38,793 - INFO - VDNS information ctest-vdns1-81353168 removed in the Control node
2021-02-22 05:04:38,793 - DEBUG - Skipping the deletion of Project ['admin_domain', 'ctest-TestvDNSBasic0-10124299']
2021-02-22 05:04:40,213 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:04:37 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestvDNSBasic0.test_vdns_ping_same_vn>
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>
args = ()
kwargs = {}

 /contrail-test/scripts/vdns/test_vdns_basic.py in test_vdns_ping_same_vn(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>)
  107                 vn_name=vn_fixt.vn_name, project_id=proj_fixt.uuid)
  108             vm_fixture[vm_name] = self.useFixture(
  109                 VMFixture(project_name=self.inputs.project_name, connections=self.connections, vn_obj=vn_quantum_obj, vm_name=vm_name,image_name='ubuntu-traffic'))
  110             assert vm_fixture[vm_name].wait_till_vm_is_up(), ('VM %s'
  111                 ' failed to come up' % (vm_name))
global VMFixture = <class 'vm_test.VMFixture'>
project_name undefined
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>
self.inputs = <common.contrail_test_init.ContrailTestInit object>
self.inputs.project_name = 'ctest-TestvDNSBasic0-10124299'
connections undefined
self.connections = <common.connections.ContrailConnections object>
vn_obj undefined
vn_quantum_obj = {'network': {'status': 'ACTIVE', 'router:externa...ec6f-461e-a435-000f1725fd66', 'description': ''}}
vm_name = 'ctest-vm1-test-33955546'
image_name undefined

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>, fixture=<VMFixture: ctest-vm1-test-33955546>)
  754                 # Gather_details worked, so raise the exception setUp
  755                 # encountered.
  756                 reraise(*exc_info)
  757         else:
  758             self.addCleanup(fixture.cleanUp)
global reraise = <function reraise>
exc_info = (<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), <traceback object>)

 /usr/local/lib/python3.6/site-packages/testtools/_compat3x.py in reraise(exc_class=<class 'keystoneauth1.exceptions.connection.ConnectFailure'>, exc_obj=ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",), exc_tb=<traceback object>, _marker=<object object>)
   13 
   14 def reraise(exc_class, exc_obj, exc_tb, _marker=object()):
   15     """Re-raise an exception received from sys.exc_info() or similar."""
   16     raise exc_obj.with_traceback(exc_tb)
   17 
exc_obj = ConnectFailure("Unable to establish connection t...ote end closed connection without response',))",)
exc_obj.with_traceback = <built-in method with_traceback of ConnectFailure object>
exc_tb = <traceback object>

 /usr/local/lib/python3.6/site-packages/testtools/testcase.py in useFixture(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fbb202befd0>, fixture=<VMFixture: ctest-vm1-test-33955546>)
  729         """
  730         try:
  731             fixture.setUp()
  732         except MultipleExceptions as e:
  733             if (fixtures is not None and
fixture = <VMFixture: ctest-vm1-test-33955546>
fixture.setUp = <bound method VMFixture.setUp of <VMFixture: ctest-vm1-test-33955546>>

 /contrail-test/fixtures/vm_test.py in setUp(self=<VMFixture: ctest-vm1-test-33955546>)
  207     def setUp(self):
  208         super(VMFixture, self).setUp()
  209         self.create()
  210 
  211     def create(self):
self = <VMFixture: ctest-vm1-test-33955546>
self.create = <bound method VMFixture.create of <VMFixture: ctest-vm1-test-33955546>>

 /contrail-test/fixtures/vm_test.py in create(self=<VMFixture: ctest-vm1-test-33955546>)
  260                     userdata=self.userdata,
  261                     port_ids=self.port_ids,
  262                     fixed_ips=self.fixed_ips)
  263                 self.created = True
  264                 self.vm_obj = objs[0]
fixed_ips undefined
self = <VMFixture: ctest-vm1-test-33955546>
self.fixed_ips = []

 /contrail-test/fixtures/openstack.py in create_vm(self=<openstack.OpenstackOrchestrator object>, vm_name='ctest-vm1-test-33955546', image_name='ubuntu-traffic', vn_objs=[{'network': {'status': 'ACTIVE', 'router:externa...ec6f-461e-a435-000f1725fd66', 'description': ''}}], **kwargs={'count': 1, 'fixed_ips': [], 'flavor': 'contrail_flavor_small', 'node_name': None, 'port_ids': [], 'project_uuid': 'a15ca110-41c7-43f5-aca4-a2c300864f84', 'sg_ids': [], 'userdata': None, 'zone': None})
  138            except Exception as e:
  139                vn_ids.append(vn.uuid) #For the case of VcenterVN obnect in vrouter gw case
  140        return self.nova_h.create_vm(vm_name=vm_name, image_name=image_name, vn_ids=vn_ids, **kwargs)
  141 
  142    def delete_vm(self, vm_obj, **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.nova_h = <nova_test.NovaHelper object>
self.nova_h.create_vm = <bound method NovaHelper.create_vm of <nova_test.NovaHelper object>>
vm_name = 'ctest-vm1-test-33955546'
image_name = 'ubuntu-traffic'
vn_ids = ['ea5c1fa6-ec6f-461e-a435-000f1725fd66']
kwargs = {'count': 1, 'fixed_ips': [], 'flavor': 'contrail_flavor_small', 'node_name': None, 'port_ids': [], 'project_uuid': 'a15ca110-41c7-43f5-aca4-a2c300864f84', 'sg_ids': [], 'userdata': None, 'zone': None}

 /contrail-test/fixtures/nova_test.py in create_vm(self=<nova_test.NovaHelper object>, project_uuid='a15ca110-41c7-43f5-aca4-a2c300864f84', image_name='ubuntu-traffic', vm_name='ctest-vm1-test-33955546', vn_ids=['ea5c1fa6-ec6f-461e-a435-000f1725fd66'], node_name='nodec9', sg_ids=[], count=1, userdata=None, flavor=<Flavor: contrail_flavor_small>, port_ids=[], fixed_ips=[], zone='nova:nodec9')
  615                                 config_drive=config_drive,
  616                                 key_name=self.key, availability_zone=zone,
  617                                 min_count=count, max_count=count, userdata=userdata)
  618         vm_objs = self.get_vm_list(name_pattern=vm_name,
  619                                    project_id=project_uuid)
min_count undefined
count = 1
max_count undefined
userdata = None

 /usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py in create(self=<novaclient.v2.servers.ServerManager object>, name='ctest-vm1-test-33955546', image=<RequestIdProxy at 0x7fbb206c5b88 for image>, flavor=<Flavor: contrail_flavor_small>, meta=None, files=None, reservation_id=False, min_count=1, max_count=1, security_groups=[], userdata=None, key_name='ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', availability_zone='nova:nodec9', block_device_mapping=None, block_device_mapping_v2=None, nics=[{'net-id': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}], scheduler_hints=None, config_drive=False, disk_config=None, admin_pass=None, access_ip_v4=None, access_ip_v6=None, trusted_image_certificates=None, host=None, hypervisor_hostname=None, **kwargs={})
 1479 
 1480         response_key = "server" if not reservation_id else "reservation_id"
 1481         return self._boot(response_key, *boot_args, **boot_kwargs)
 1482 
 1483     @api_versions.wraps("2.0", "2.18")
self = <novaclient.v2.servers.ServerManager object>
self._boot = <bound method ServerManager._boot of <novaclient.v2.servers.ServerManager object>>
response_key = 'server'
boot_args = ['ctest-vm1-test-33955546', <RequestIdProxy at 0x7fbb206c5b88 for image>, <Flavor: contrail_flavor_small>]
boot_kwargs = {'access_ip_v4': None, 'access_ip_v6': None, 'admin_pass': None, 'availability_zone': 'nova:nodec9', 'config_drive': False, 'disk_config': None, 'files': None, 'host': None, 'hypervisor_hostname': None, 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', ...}

 /usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py in _boot(self=<novaclient.v2.servers.ServerManager object>, response_key='server', name='ctest-vm1-test-33955546', image=<RequestIdProxy at 0x7fbb206c5b88 for image>, flavor=<Flavor: contrail_flavor_small>, meta=None, files=None, userdata=None, reservation_id=False, return_raw=False, min_count=1, max_count=1, security_groups=[], key_name='ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', availability_zone='nova:nodec9', block_device_mapping=None, block_device_mapping_v2=None, nics=[{'net-id': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}], scheduler_hints=None, config_drive=False, admin_pass=None, disk_config=None, access_ip_v4=None, access_ip_v6=None, description=None, tags=None, trusted_image_certificates=None, host=None, hypervisor_hostname=None, **kwargs={})
  844 
  845         return self._create('/servers', body, response_key,
  846                             return_raw=return_raw, **kwargs)
  847 
  848     def get(self, server):
return_raw = False
kwargs = {}

 /usr/local/lib/python3.6/site-packages/novaclient/base.py in _create(self=<novaclient.v2.servers.ServerManager object>, url='/servers', body={'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, response_key='server', return_raw=False, obj_class=None, **kwargs={})
  362                 obj_class=None, **kwargs):
  363         self.run_hooks('modify_body_for_create', body, **kwargs)
  364         resp, body = self.api.client.post(url, body=body)
  365         if return_raw:
  366             return self.convert_into_with_meta(body[response_key], resp)
resp undefined
body = {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}
self = <novaclient.v2.servers.ServerManager object>
self.api = <novaclient.v2.client.Client object>
self.api.client = <novaclient.client.SessionClient object>
self.api.client.post = <bound method Adapter.post of <novaclient.client.SessionClient object>>
url = '/servers'

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in post(self=<novaclient.client.SessionClient object>, url='/servers', **kwargs={'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}})
  390 
  391     def post(self, url, **kwargs):
  392         return self.request(url, 'POST', **kwargs)
  393 
  394     def put(self, url, **kwargs):
self = <novaclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <novaclient.client.SessionClient object>>
url = '/servers'
kwargs = {'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}}

 /usr/local/lib/python3.6/site-packages/novaclient/client.py in request(self=<novaclient.client.SessionClient object>, url='/servers', method='POST', **kwargs={'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}})
   70                                                             method,
   71                                                             raise_exc=False,
   72                                                             **kwargs)
   73 
   74         # TODO(andreykurilin): uncomment this line, when we will be able to
kwargs = {'body': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<novaclient.client.SessionClient object>, *args=('/servers', 'POST'), **kwargs={'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'json': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'raise_exc': False})
  543             pass
  544 
  545         resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  546 
  547         try:
resp undefined
builtinsuper = <class 'super'>
global LegacyJsonAdapter = <class 'keystoneauth1.adapter.LegacyJsonAdapter'>
self = <novaclient.client.SessionClient object>
).request = <bound method SessionClient.request of <novaclient.client.SessionClient object>>
args = ('/servers', 'POST')
kwargs = {'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'json': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<novaclient.client.SessionClient object>, url='/servers', method='POST', **kwargs={'client_name': 'python-novaclient', 'client_version': '16.0.0', 'endpoint_filter': {'interface': 'publicURL', 'region_name': 'RegionOne', 'service_type': 'compute'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'json': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-novaclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <novaclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/servers'
method = 'POST'
kwargs = {'client_name': 'python-novaclient', 'client_version': '16.0.0', 'endpoint_filter': {'interface': 'publicURL', 'region_name': 'RegionOne', 'service_type': 'compute'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'json': {'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-novaclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.12:8774/v2.1/servers', method='POST', json={'server': {'availability_zone': 'nova:nodec9', 'flavorRef': '36038605-fef3-42cf-9207-d7aadf7c58ca', 'imageRef': 'cc19857a-ed17-4faf-844d-a74511197166', 'key_name': 'ctest_ctest-TestvDNSBasic0-10124299ctest-TestvDNSBasic0-10124299key1', 'max_count': 1, 'min_count': 1, 'name': 'ctest-vm1-test-33955546', 'networks': [{'uuid': 'ea5c1fa6-ec6f-461e-a435-000f1725fd66'}]}}, original_ip=None, user_agent='python-novaclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'publicURL', 'region_name': 'RegionOne', 'service_type': 'compute'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name='python-novaclient', client_version='16.0.0', microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"server": {"name": "ctest-vm1-test-33955546", "...uuid": "ea5c1fa6-ec6f-461e-a435-000f1725fd66"}]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7fbb1e819710>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"server": {"name": "ctest-vm1-test-33955546", "...uuid": "ea5c1fa6-ec6f-461e-a435-000f1725fd66"}]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.12:8774/v2.1/servers', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"server": {"name": "ctest-vm1-test-33955546", "...uuid": "ea5c1fa6-ec6f-461e-a435-000f1725fd66"}]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-novaclient', 'X-Auth-Token': 'e963e109fc7e4f048d1090c233c840a9'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.12:8774/v2.1/servers: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/vdns/test_vdns_basic.py", line 109, in test_vdns_ping_same_vn
    VMFixture(project_name=self.inputs.project_name, connections=self.connections, vn_obj=vn_quantum_obj, vm_name=vm_name,image_name='ubuntu-traffic'))
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 756, in useFixture
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/usr/local/lib/python3.6/site-packages/testtools/testcase.py", line 731, in useFixture
    fixture.setUp()
  File "/contrail-test/fixtures/vm_test.py", line 209, in setUp
    self.create()
  File "/contrail-test/fixtures/vm_test.py", line 262, in create
    fixed_ips=self.fixed_ips)
  File "/contrail-test/fixtures/openstack.py", line 140, in create_vm
    return self.nova_h.create_vm(vm_name=vm_name, image_name=image_name, vn_ids=vn_ids, **kwargs)
  File "/contrail-test/fixtures/nova_test.py", line 617, in create_vm
    min_count=count, max_count=count, userdata=userdata)
  File "/usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1481, in create
    return self._boot(response_key, *boot_args, **boot_kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/v2/servers.py", line 846, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/base.py", line 364, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/novaclient/client.py", line 72, in request
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 545, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.12:8774/v2.1/servers: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:04:40,250 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:04:40,250 - INFO - 
2021-02-22 05:04:40,251 - INFO - END TEST : test_vdns_ping_same_vn : FAILED[0:01:44]
2021-02-22 05:04:40,251 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:04:45,373 - INFO - Deleted project: ctest-TestvDNSBasic0-10124299, ID : a15ca110-41c7-43f5-aca4-a2c300864f84 
2021-02-22 05:26:11,421 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:26:11,449 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:26:11,809 - INFO - Project ctest-TestvDNSBasic0-52899157 not found, creating it
2021-02-22 05:26:12,468 - INFO - Created Project:ctest-TestvDNSBasic0-52899157, ID : ee5bc536-3df3-4fc7-9e69-6882a88ba8e9 
2021-02-22 05:26:16,908 - INFO - ================================================================================
2021-02-22 05:26:16,908 - INFO - STARTING TEST    : test_vdns_ping_same_vn
2021-02-22 05:26:16,908 - INFO - TEST DESCRIPTION : 
        Test:- Test vdns functionality. On VM launch agent should dynamically update dns records to dns agent
            1.  Create vDNS server
            2.  Create IPAM using above vDNS data
            3.  Create VN using above IPAM and launch 2 VM's within it
            4.  Ping between these 2 VM's using dns name
            5.  Try to delete vDNS server which has IPAM back-reference[Negative case]
            6.  Add CNAME VDNS record for vm1-test and verify we able to ping by alias name
        Pass criteria: Step 4,5 and 6 should pass

        Maintainer: cf-test@juniper.net
        
2021-02-22 05:26:18,281 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:26:18,282 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:26:18,282 - INFO - 
2021-02-22 05:26:19,464 - INFO - Using existing project ['admin_domain', 'ctest-TestvDNSBasic0-52899157'](ee5bc536-3df3-4fc7-9e69-6882a88ba8e9)
2021-02-22 05:26:19,527 - DEBUG - Creating VDNS : ctest-vdns1-12577194
2021-02-22 05:26:19,626 - DEBUG - VDNS: ['admin_domain', 'ctest-vdns1-12577194'] created succesfully
2021-02-22 05:26:19,627 - DEBUG - Verify VDNS entry is shown in control node
2021-02-22 05:26:19,627 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-12577194
2021-02-22 05:26:19,646 - DEBUG - Requesting: https://192.168.7.29:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-12577194
2021-02-22 05:26:20,417 - DEBUG - Requesting: https://192.168.7.34:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-12577194
2021-02-22 05:26:20,434 - DEBUG - Verify VDNS entry is shown in the API server
2021-02-22 05:26:20,435 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:26:21,248 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:26:21,334 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:26:21,446 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-DNS/9dd5c2cd-2018-446b-ab54-53684f91514f
2021-02-22 05:26:22,467 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestvDNSBasic0-52899157', 'ctest-vn1-vdns-11163550'], 'name': 'ctest-vn1-vdns-11163550', 'admin_state_up': True, 'tenant_id': 'ee5bc5363df34fc79e696882a88ba8e9', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'ee5bc5363df34fc79e696882a88ba8e9', 'id': 'd6f1c5c5-7e74-4987-86bd-1650a10ae8f0', 'description': ''}}
2021-02-22 05:26:23,217 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'd6f1c5c5-7e74-4987-86bd-1650a10ae8f0', 'tenant_id': 'ee5bc5363df34fc79e696882a88ba8e9', 'created_at': '2021-02-22T05:26:22.415276', 'dns_nameservers': [], 'updated_at': '2021-02-22T05:26:22.415276', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '10.10.10.2', 'end': '10.10.10.254'}], 'gateway_ip': '10.10.10.1', 'dns_server_address': '10.10.10.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '10.10.10.0/24', 'id': '0f693528-b532-487f-83cb-89a39be698c9'}}
2021-02-22 05:26:23,270 - INFO - Created VN ctest-vn1-vdns-11163550
2021-02-22 05:26:23,307 - DEBUG - VN ctest-vn1-vdns-11163550 UUID is d6f1c5c5-7e74-4987-86bd-1650a10ae8f0
2021-02-22 05:26:23,872 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-22 05:27:54,180 - INFO - Deleting VN ctest-vn1-vdns-11163550 
2021-02-22 05:28:07,983 - DEBUG - Deleting VDNS Entry: ctest-vdns1-12577194
2021-02-22 05:28:08,071 - INFO - VDNS info: ['admin_domain', 'ctest-vdns1-12577194'] deleted successfully.
2021-02-22 05:28:08,072 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-22 05:28:08,092 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:28:08,133 - DEBUG - VDNS information not found in API server
2021-02-22 05:28:08,133 - INFO - VDNS information ctest-vdns1-12577194 removed from the API Server
2021-02-22 05:28:08,134 - DEBUG - Requesting: https://192.168.7.20:8083/Snh_IFMapTableShowReq?table_name=virtual-DNS&search_string=virtual-DNS:admin_domain:ctest-vdns1-12577194
2021-02-22 05:28:08,193 - INFO - VDNS information ctest-vdns1-12577194 removed in the Control node
2021-02-22 05:28:08,193 - DEBUG - Skipping the deletion of Project ['admin_domain', 'ctest-TestvDNSBasic0-52899157']
2021-02-23 05:55:50,611 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:55:50,638 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-23 05:55:51,022 - INFO - Project ctest-TestvDNSBasic0-57678938 not found, creating it
2021-02-23 05:55:51,661 - INFO - Created Project:ctest-TestvDNSBasic0-57678938, ID : 75cb406d-fc4b-49f4-bca2-8b7dde9ed128 
2021-02-23 05:55:55,986 - INFO - ================================================================================
2021-02-23 05:55:55,986 - INFO - STARTING TEST    : test_vdns_ping_same_vn
2021-02-23 05:55:55,986 - INFO - TEST DESCRIPTION : 
        Test:- Test vdns functionality. On VM launch agent should dynamically update dns records to dns agent
            1.  Create vDNS server
            2.  Create IPAM using above vDNS data
            3.  Create VN using above IPAM and launch 2 VM's within it
            4.  Ping between these 2 VM's using dns name
            5.  Try to delete vDNS server which has IPAM back-reference[Negative case]
            6.  Add CNAME VDNS record for vm1-test and verify we able to ping by alias name
        Pass criteria: Step 4,5 and 6 should pass

        Maintainer: cf-test@juniper.net
        
2021-02-23 05:55:57,342 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-23 05:55:57,342 - INFO - Initial checks done. Running the testcase now
2021-02-23 05:55:57,342 - INFO - 
2021-02-23 05:55:58,645 - INFO - Using existing project ['admin_domain', 'ctest-TestvDNSBasic0-57678938'](75cb406d-fc4b-49f4-bca2-8b7dde9ed128)
2021-02-23 05:55:58,713 - DEBUG - Creating VDNS : ctest-vdns1-67468773
2021-02-23 05:55:58,837 - DEBUG - VDNS: ['admin_domain', 'ctest-vdns1-67468773'] created succesfully
2021-02-23 05:55:58,837 - DEBUG - Verify VDNS entry is shown in control node
2021-02-23 05:55:58,974 - DEBUG - Verify VDNS entry is shown in the API server
2021-02-23 05:55:58,974 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:55:59,752 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-23 05:55:59,829 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:55:59,884 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-DNS/06e123c9-078a-4e6f-8c9b-a6db5d8b8e4c
2021-02-23 05:56:02,299 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'name': 'ctest-vn1-vdns-13300671', 'admin_state_up': True, 'tenant_id': '75cb406dfc4b49f4bca28b7dde9ed128', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '75cb406dfc4b49f4bca28b7dde9ed128', 'id': '58c30638-4656-4730-96bb-e51dd2948e33', 'description': ''}}
2021-02-23 05:57:32,383 - DEBUG - Deleting VDNS Entry: ctest-vdns1-67468773
2021-02-23 05:57:32,409 - DEBUG - Skipping the deletion of Project ['admin_domain', 'ctest-TestvDNSBasic0-57678938']
2021-02-23 05:57:32,550 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:34,670 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:36,777 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:38,883 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:40,998 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:43,117 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:45,251 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:47,404 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:49,524 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:51,639 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:53,755 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:55,865 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:57:58,003 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:00,121 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:02,239 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:04,459 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:06,573 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:08,713 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:10,827 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:12,939 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:15,054 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:17,167 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:19,286 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:21,409 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:23,523 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:25,641 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:27,745 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:29,877 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:31,995 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:34,124 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:36,256 - WARNING - Project ctest-TestvDNSBasic0-57678938 still has VNs [{'to': ['admin_domain', 'ctest-TestvDNSBasic0-57678938', 'ctest-vn1-vdns-13300671'], 'href': 'https://192.168.7.34:8082/virtual-network/58c30638-4656-4730-96bb-e51dd2948e33', 'uuid': '58c30638-4656-4730-96bb-e51dd2948e33'}] before deletion
2021-02-23 05:58:36,256 - WARNING - One or more references still present, will not delete the project ctest-TestvDNSBasic0-57678938
2021-02-24 06:25:40,613 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:25:40,645 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-24 06:25:41,503 - INFO - Project ctest-TestvDNSBasic0-54333399 not found, creating it
2021-02-24 06:25:42,241 - INFO - Created Project:ctest-TestvDNSBasic0-54333399, ID : 387c65ad-8dd7-4aea-9ed1-1d3ccccd9ff9 
2021-02-24 06:25:45,830 - INFO - ================================================================================
2021-02-24 06:25:45,830 - INFO - STARTING TEST    : test_vdns_ping_same_vn
2021-02-24 06:25:45,830 - INFO - TEST DESCRIPTION : 
        Test:- Test vdns functionality. On VM launch agent should dynamically update dns records to dns agent
            1.  Create vDNS server
            2.  Create IPAM using above vDNS data
            3.  Create VN using above IPAM and launch 2 VM's within it
            4.  Ping between these 2 VM's using dns name
            5.  Try to delete vDNS server which has IPAM back-reference[Negative case]
            6.  Add CNAME VDNS record for vm1-test and verify we able to ping by alias name
        Pass criteria: Step 4,5 and 6 should pass

        Maintainer: cf-test@juniper.net
        
2021-02-24 06:25:47,875 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-24 06:25:47,876 - INFO - Initial checks done. Running the testcase now
2021-02-24 06:25:47,876 - INFO - 
2021-02-24 06:25:49,195 - INFO - Using existing project ['admin_domain', 'ctest-TestvDNSBasic0-54333399'](387c65ad-8dd7-4aea-9ed1-1d3ccccd9ff9)
2021-02-24 06:25:49,263 - DEBUG - Creating VDNS : ctest-vdns1-68232433
2021-02-24 06:25:49,367 - DEBUG - VDNS: ['admin_domain', 'ctest-vdns1-68232433'] created succesfully
2021-02-24 06:25:49,367 - DEBUG - Verify VDNS entry is shown in control node
2021-02-24 06:25:49,464 - DEBUG - Verify VDNS entry is shown in the API server
2021-02-24 06:25:49,465 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:25:51,683 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:25:51,755 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:25:51,808 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-DNS/60a4c883-770f-42ad-90e3-1033ad81b72d
2021-02-24 06:25:52,776 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestvDNSBasic0-54333399', 'ctest-vn1-vdns-48027156'], 'name': 'ctest-vn1-vdns-48027156', 'admin_state_up': True, 'tenant_id': '387c65ad8dd74aea9ed11d3ccccd9ff9', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '387c65ad8dd74aea9ed11d3ccccd9ff9', 'id': 'c4036f79-8cc5-4ace-aa77-dc04971c9493', 'description': ''}}
2021-02-24 06:25:53,445 - ERROR - Neutron Exception while creating subnet for vn with id c4036f79-8cc5-4ace-aa77-dc04971c9493
Traceback (most recent call last):
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
neutronclient.common.exceptions.InternalServerError: The server has either erred or is incapable of performing the requested operation.<br /><br />



Neutron server returns request_ids: ['req-14dff486-1a6e-424f-914e-94a9ca449b3f']
2021-02-24 06:25:53,495 - INFO - Created VN ctest-vn1-vdns-48027156
2021-02-24 06:25:53,521 - DEBUG - VN ctest-vn1-vdns-48027156 UUID is c4036f79-8cc5-4ace-aa77-dc04971c9493
2021-02-24 06:25:54,274 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-24 06:25:56,963 - INFO - VM ([<Server: ctest-vm1-test-48113327>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:25:56,964 - INFO - Waiting for VM ctest-vm1-test-48113327 to be up..
2021-02-24 06:25:57,037 - DEBUG - VM <Server: ctest-vm1-test-48113327> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:26:02,099 - DEBUG - VM <Server: ctest-vm1-test-48113327> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:26:07,225 - DEBUG - VM <Server: ctest-vm1-test-48113327> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:26:12,447 - DEBUG - VM <Server: ctest-vm1-test-48113327> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:26:17,783 - DEBUG - VM <Server: ctest-vm1-test-48113327> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:26:22,986 - DEBUG - VM <Server: ctest-vm1-test-48113327> is in ACTIVE state now
2021-02-24 06:26:22,986 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:26:23,188 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:26:23,188 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:26:23,389 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:28,587 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:33,799 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:38,997 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:44,208 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:49,418 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:54,615 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:26:59,810 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:05,025 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:10,509 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:15,717 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:15,717 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:27:17,719 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:27:17,925 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:27:17,925 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:27:18,121 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:23,519 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:28,717 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:33,912 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:39,113 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:44,305 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:49,501 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:54,693 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:27:59,882 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:05,102 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:10,306 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:10,307 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:28:12,308 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:28:12,511 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:28:12,511 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:28:12,718 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:17,932 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:23,117 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:28,315 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:33,520 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:38,748 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:43,945 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:49,144 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:54,344 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:28:59,550 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:04,749 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:04,749 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:29:06,750 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:29:06,954 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:29:06,954 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:29:07,154 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:12,360 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:17,568 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:22,771 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:27,978 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:33,164 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:38,364 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:43,548 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:48,721 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:53,919 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:59,127 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:29:59,128 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:30:01,129 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:30:01,335 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:30:01,335 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:30:01,544 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:06,765 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:11,963 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:17,169 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:22,383 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:27,600 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:32,801 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:38,000 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:43,421 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:49,247 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:54,653 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:30:54,653 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:30:56,654 - INFO - VM name : ctest-vm1-test-48113327
2021-02-24 06:30:56,927 - DEBUG - VM ctest-vm1-test-48113327 ID is 3c9b83a7-a8fd-4d99-9763-0c0436749c62
2021-02-24 06:30:56,928 - DEBUG - VM ctest-vm1-test-48113327 launched on Node nodec9.maas
2021-02-24 06:30:57,135 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:02,333 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:07,537 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:12,747 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:17,931 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:23,135 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:28,332 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:33,532 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:38,740 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:43,944 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:49,158 - ERROR - VM does not seem to have got an IP in VN ctest-vn1-vdns-48027156
2021-02-24 06:31:49,158 - ERROR - VM didnt seem to have got any IP
2021-02-24 06:31:49,277 - DEBUG - VM ctest-vm1-test-48113327 does not seem to be fully up
2021-02-24 06:31:49,620 - DEBUG - Console output: [    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.2.0-35-virtual (buildd@allspice) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #55-Ubuntu SMP Wed Dec 5 18:02:05 UTC 2012 (Ubuntu 3.2.0-35.55-virtual 3.2.34)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-3.2.0-35-virtual root=UUID=02147f18-c4e2-47d4-ba41-a162651517cb ro console=ttyS0 console=tty0 rootdelay=1800
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] BIOS-provided physical RAM map:
[    0.000000]  BIOS-e820: 0000000000000000 - 000000000009fc00 (usable)
[    0.000000]  BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  BIOS-e820: 00000000000f0000 - 0000000000100000 (reserved)
[    0.000000]  BIOS-e820: 0000000000100000 - 000000003ffdc000 (usable)
[    0.000000]  BIOS-e820: 000000003ffdc000 - 0000000040000000 (reserved)
[    0.000000]  BIOS-e820: 00000000fffc0000 - 0000000100000000 (reserved)
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] DMI 2.8 present.
[    0.000000] No AGP bridge found
[    0.000000] last_pfn = 0x3ffdc max_arch_pfn = 0x400000000
[    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
[    0.000000] found SMP MP-table at [ffff8800000f6a80] f6a80
[    0.000000] Using GB pages for direct mapping
[    0.000000] init_memory_mapping: 0000000000000000-000000003ffdc000
[    0.000000] RAMDISK: 3776e000 - 37baf000
[    0.000000] ACPI: RSDP 00000000000f6880 00014 (v00 BOCHS )
[    0.000000] ACPI: RSDT 000000003ffe15c9 00030 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACP 000000003ffe1425 00074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 000000003ffe0040 013E5 (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACS 000000003ffe0000 00040
[    0.000000] ACPI: APIC 000000003ffe1519 00078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[    0.000000] ACPI: HPET 000000003ffe1591 00038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at 0000000000000000-000000003ffdc000
[    0.000000] Initmem setup node 0 0000000000000000-000000003ffdc000
[    0.000000]   NODE_DATA [000000003ffd7000 - 000000003ffdbfff]
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000010 -> 0x00001000
[    0.000000]   DMA32    0x00001000 -> 0x00100000
[    0.000000]   Normal   empty
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[2] active PFN ranges
[    0.000000]     0: 0x00000010 -> 0x0000009f
[    0.000000]     0: 0x00000100 -> 0x0003ffdc
[    0.000000] ACPI: PM-Timer IO Port: 0x608
[    0.000000] ACPI: LAPIC (acpi_id[0x00] lapic_id[0x00] enabled)
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[    0.000000] ACPI: IOAPIC (id[0x00] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 0, version 32, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x8086a201 base: 0xfed00000
[    0.000000] SMP: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: 000000000009f000 - 00000000000a0000
[    0.000000] PM: Registered nosave memory: 00000000000a0000 - 00000000000f0000
[    0.000000] PM: Registered nosave memory: 00000000000f0000 - 0000000000100000
[    0.000000] Allocating PCI resources starting at 40000000 (gap: 40000000:bffc0000)
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] setup_percpu: NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 28 pages/cpu @ffff88003fc00000 s82880 r8192 d23616 u2097152
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 257894
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.2.0-35-virtual root=UUID=02147f18-c4e2-47d4-ba41-a162651517cb ro console=ttyS0 console=tty0 rootdelay=1800
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] xsave/xrstor: enabled xstate_bv 0x3, cntxt size 0xa88
[    0.000000] Checking aperture...
[    0.000000] No AGP bridge found
[    0.000000] Memory: 1011328k/1048432k available (6540k kernel code, 452k absent, 36652k reserved, 6652k data, 924k init)
[    0.000000] SLUB: Genslabs=15, HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	RCU dyntick-idle grace-period acceleration is enabled.
[    0.000000] NR_IRQS:4352 nr_irqs:256 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty0] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] allocated 8388608 bytes of page_cgroup
[    0.000000] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000000] Fast TSC calibration using PIT
[    0.000000] Detected 3099.919 MHz processor.
[    0.012710] Calibrating delay loop (skipped), value calculated using timer frequency.. 6199.83 BogoMIPS (lpj=12399676)
[    0.016610] pid_max: default: 32768 minimum: 301
[    0.021064] Security Framework initialized
[    0.024787] AppArmor: AppArmor initialized
[    0.025219] Yama: becoming mindful.
[    0.031113] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.033382] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.034818] Mount-cache hash table entries: 256
[    0.044045] Initializing cgroup subsys cpuacct
[    0.044622] Initializing cgroup subsys memory
[    0.045692] Initializing cgroup subsys devices
[    0.046103] Initializing cgroup subsys freezer
[    0.046454] Initializing cgroup subsys blkio
[    0.046817] Initializing cgroup subsys perf_event
[    0.050857] mce: CPU supports 10 MCE banks
[    0.053664] SMP alternatives: switching to UP code
[    0.348411] Freeing SMP alternatives: 24k freed
[    0.349328] ACPI: Core revision 20110623
[    0.375333] ftrace: allocating 27024 entries in 106 pages
[    0.393635] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.434506] CPU0: AMD EPYC Processor stepping 02
[    0.436026] Performance Events: Broken PMU hardware detected, using software events only.
[    0.440367] NMI watchdog disabled (cpu0): hardware events not enabled
[    0.441477] Brought up 1 CPUs
[    0.442128] Total of 1 processors activated (6199.83 BogoMIPS).
[    0.456828] devtmpfs: initialized
[    0.464858] EVM: security.selinux
[    0.465182] EVM: security.SMACK64
[    0.465486] EVM: security.capability
[    0.475757] print_constraints: dummy: 
[    0.476919] RTC time:  6:26:26, date: 02/24/21
[    0.478608] NET: Registered protocol family 16
[    0.483361] Extended Config Space enabled on 0 nodes
[    0.484361] ACPI: bus type pci registered
[    0.487053] PCI: Using configuration type 1 for base access
[    0.487785] PCI: Using configuration type 1 for extended access
[    0.505020] bio: create slab <bio-0> at 0
[    0.507961] ACPI: Added _OSI(Module Device)
[    0.508075] ACPI: Added _OSI(Processor Device)
[    0.508957] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.509483] ACPI: Added _OSI(Processor Aggregator Device)
[    0.533506] ACPI: Interpreter enabled
[    0.533917] ACPI: (supports S0 S3 S4 S5)
[    0.535190] ACPI: Using IOAPIC for interrupt routing
[    0.574551] ACPI: No dock devices found.
[    0.575007] HEST: Table not found.
[    0.575729] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.577646] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.580873] pci_root PNP0A03:00: host bridge window [io  0x0000-0x0cf7]
[    0.581452] pci_root PNP0A03:00: host bridge window [io  0x0d00-0xffff]
[    0.582655] pci_root PNP0A03:00: host bridge window [mem 0x000a0000-0x000bffff]
[    0.583979] pci_root PNP0A03:00: host bridge window [mem 0x40000000-0xfebfffff]
[    0.584063] pci_root PNP0A03:00: host bridge window [mem 0x100000000-0x17fffffff]
[    0.595923] pci 0000:00:01.3: quirk: [io  0x0600-0x063f] claimed by PIIX4 ACPI
[    0.596114] pci 0000:00:01.3: quirk: [io  0x0700-0x070f] claimed by PIIX4 SMB
[    0.954979]  pci0000:00: Requesting ACPI _OSC control (0x1d)
[    0.955565]  pci0000:00: ACPI _OSC request failed (AE_NOT_FOUND), returned control mask: 0x1d
[    0.956059] ACPI _OSC control for PCIe not granted, disabling ASPM
[    0.991908] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[    0.993191] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[    0.994309] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[    0.995372] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[    0.996463] ACPI: PCI Interrupt Link [LNKS] (IRQs *9)
[    1.000602] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    1.001241] vgaarb: loaded
[    1.001489] vgaarb: bridge control possible 0000:00:02.0
[    1.004190] i2c-core: driver [aat2870] using legacy suspend method
[    1.004620] i2c-core: driver [aat2870] using legacy resume method
[    1.006163] SCSI subsystem initialized
[    1.008351] usbcore: registered new interface driver usbfs
[    1.009071] usbcore: registered new interface driver hub
[    1.009831] usbcore: registered new device driver usb
[    1.012233] PCI: Using ACPI for IRQ routing
[    1.019211] NetLabel: Initializing
[    1.019569] NetLabel:  domain hash size = 128
[    1.019934] NetLabel:  protocols = UNLABELED CIPSOv4
[    1.021070] NetLabel:  unlabeled traffic allowed by default
[    1.022821] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0
[    1.023523] hpet0: 3 comparators, 64-bit 100.000000 MHz counter
[    1.028104] Switching to clocksource hpet
[    1.127714] AppArmor: AppArmor Filesystem Enabled
[    1.128952] pnp: PnP ACPI init
[    1.129390] ACPI: bus type pnp registered
[    1.139573] pnp: PnP ACPI: found 10 devices
[    1.140007] ACPI: ACPI bus type pnp unregistered
[    1.170735] NET: Registered protocol family 2
[    1.174793] IP route cache hash table entries: 32768 (order: 6, 262144 bytes)
[    1.180903] TCP established hash table entries: 131072 (order: 9, 2097152 bytes)
[    1.183668] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    1.185204] TCP: Hash tables configured (established 131072 bind 65536)
[    1.186445] TCP reno registered
[    1.186857] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    1.188016] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    1.189941] NET: Registered protocol family 1
[    1.191770] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    1.192395] pci 0000:00:01.0: PIIX3: Enabling Passive Release
[    1.193628] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    1.196888] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
[    1.197620] pci 0000:00:01.2: PCI INT D -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.199031] pci 0000:00:01.2: PCI INT D disabled
[    1.209655] Trying to unpack rootfs image as initramfs...
[    1.225155] audit: initializing netlink socket (disabled)
[    1.226245] type=2000 audit(1614147986.220:1): initialized
[    1.344590] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    1.385752] VFS: Disk quotas dquot_6.5.2
[    1.386656] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    1.401236] fuse init (API version 7.17)
[    1.402923] msgmni has been set to 1975
[    1.425480] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.432836] io scheduler noop registered
[    1.433313] io scheduler deadline registered (default)
[    1.434149] io scheduler cfq registered
[    1.436693] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    1.438157] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    1.441506] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.442630] ACPI: Power Button [PWRF]
[    1.462907] ERST: Table is not found!
[    1.463353] GHES: HEST is not enabled!
[    1.469245] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 10
[    1.469856] virtio-pci 0000:00:03.0: PCI INT A -> Link[LNKC] -> GSI 10 (level, high) -> IRQ 10
[    1.471967] virtio-pci 0000:00:04.0: PCI INT A -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.481734] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
[    1.482327] virtio-pci 0000:00:05.0: PCI INT A -> Link[LNKA] -> GSI 10 (level, high) -> IRQ 10
[    1.484407] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
[    1.484935] virtio-pci 0000:00:06.0: PCI INT A -> Link[LNKB] -> GSI 11 (level, high) -> IRQ 11
[    1.487372] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    1.510551] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.585198] 00:05: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.614453] Linux agpgart interface v0.103
[    1.647626] brd: module loaded
[    1.659456] loop: module loaded
[    1.717479]  vda: vda1
[    1.748863] scsi0 : ata_piix
[    1.750567] scsi1 : ata_piix
[    1.751455] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc0e0 irq 14
[    1.752164] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc0e8 irq 15
[    1.757941] Fixed MDIO Bus: probed
[    1.758568] tun: Universal TUN/TAP device driver, 1.6
[    1.759003] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.765368] PPP generic driver version 2.4.2
[    1.776984] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.777828] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.778519] uhci_hcd: USB Universal Host Controller Interface driver
[    1.779261] uhci_hcd 0000:00:01.2: PCI INT D -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.780704] uhci_hcd 0000:00:01.2: UHCI Host Controller
[    1.788702] uhci_hcd 0000:00:01.2: new USB bus registered, assigned bus number 1
[    1.790015] uhci_hcd 0000:00:01.2: irq 11, io base 0x0000c080
[    1.802697] hub 1-0:1.0: USB hub found
[    1.803450] hub 1-0:1.0: 2 ports detected
[    1.806530] usbcore: registered new interface driver libusual
[    1.807630] i8042: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[    1.810836] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.811477] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.825396] mousedev: PS/2 mouse device common for all mice
[    1.828948] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[    1.830689] rtc_cmos 00:01: RTC can wake from S4
[    1.840798] rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
[    1.841864] rtc0: alarms up to one day, y3k, 114 bytes nvram, hpet irqs
[    1.844593] device-mapper: uevent: version 1.0.3
[    1.852584] device-mapper: ioctl: 4.22.0-ioctl (2011-10-19) initialised: dm-devel@redhat.com
[    1.853904] cpuidle: using governor ladder
[    1.854353] cpuidle: using governor menu
[    1.854730] EFI Variables Facility v0.08 2004-May-17
[    1.857252] TCP cubic registered
[    1.858759] NET: Registered protocol family 10
[    1.867095] NET: Registered protocol family 17
[    1.867671] Registering the dns_resolver key type
[    1.885782] registered taskstats version 1
[    1.964623] Freeing initrd memory: 4356k freed
[    2.119960] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    2.217046] Refined TSC clocksource calibration: 3099.913 MHz.
[    2.218015] Switching to clocksource tsc
[    2.252975]   Magic number: 9:786:418
[    2.254116] rtc_cmos 00:01: setting system clock to 2021-02-24 06:26:28 UTC (1614147988)
[    2.256001] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    2.256624] EDD information not available.
[    2.270404] Freeing unused kernel memory: 924k freed
[    2.285911] Write protecting the kernel read-only data: 12288k
[    2.312630] Freeing unused kernel memory: 1632k freed
[    2.332831] Freeing unused kernel memory: 1200k freed
[    2.986595] udevd[83]: starting version 175
[    6.463393] FDC 0 is a S82078B
[    6.670212] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: (null)
[   13.939792] EXT4-fs (vda1): re-mounted. Opts: (null)

Ubuntu 12.04.1 LTS ctest-vm1-test-48113327 ttyS0

ctest-vm1-test-48113327 login: 
2021-02-24 06:31:49,620 - ERROR - VM ctest-vm1-test-48113327 does not seem to be fully up. Check logs
2021-02-24 06:31:49,944 - DEBUG - [    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.2.0-35-virtual (buildd@allspice) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #55-Ubuntu SMP Wed Dec 5 18:02:05 UTC 2012 (Ubuntu 3.2.0-35.55-virtual 3.2.34)
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-3.2.0-35-virtual root=UUID=02147f18-c4e2-47d4-ba41-a162651517cb ro console=ttyS0 console=tty0 rootdelay=1800
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] BIOS-provided physical RAM map:
[    0.000000]  BIOS-e820: 0000000000000000 - 000000000009fc00 (usable)
[    0.000000]  BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  BIOS-e820: 00000000000f0000 - 0000000000100000 (reserved)
[    0.000000]  BIOS-e820: 0000000000100000 - 000000003ffdc000 (usable)
[    0.000000]  BIOS-e820: 000000003ffdc000 - 0000000040000000 (reserved)
[    0.000000]  BIOS-e820: 00000000fffc0000 - 0000000100000000 (reserved)
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] DMI 2.8 present.
[    0.000000] No AGP bridge found
[    0.000000] last_pfn = 0x3ffdc max_arch_pfn = 0x400000000
[    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
[    0.000000] found SMP MP-table at [ffff8800000f6a80] f6a80
[    0.000000] Using GB pages for direct mapping
[    0.000000] init_memory_mapping: 0000000000000000-000000003ffdc000
[    0.000000] RAMDISK: 3776e000 - 37baf000
[    0.000000] ACPI: RSDP 00000000000f6880 00014 (v00 BOCHS )
[    0.000000] ACPI: RSDT 000000003ffe15c9 00030 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACP 000000003ffe1425 00074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 000000003ffe0040 013E5 (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACS 000000003ffe0000 00040
[    0.000000] ACPI: APIC 000000003ffe1519 00078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[    0.000000] ACPI: HPET 000000003ffe1591 00038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at 0000000000000000-000000003ffdc000
[    0.000000] Initmem setup node 0 0000000000000000-000000003ffdc000
[    0.000000]   NODE_DATA [000000003ffd7000 - 000000003ffdbfff]
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000010 -> 0x00001000
[    0.000000]   DMA32    0x00001000 -> 0x00100000
[    0.000000]   Normal   empty
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[2] active PFN ranges
[    0.000000]     0: 0x00000010 -> 0x0000009f
[    0.000000]     0: 0x00000100 -> 0x0003ffdc
[    0.000000] ACPI: PM-Timer IO Port: 0x608
[    0.000000] ACPI: LAPIC (acpi_id[0x00] lapic_id[0x00] enabled)
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[    0.000000] ACPI: IOAPIC (id[0x00] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 0, version 32, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x8086a201 base: 0xfed00000
[    0.000000] SMP: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: 000000000009f000 - 00000000000a0000
[    0.000000] PM: Registered nosave memory: 00000000000a0000 - 00000000000f0000
[    0.000000] PM: Registered nosave memory: 00000000000f0000 - 0000000000100000
[    0.000000] Allocating PCI resources starting at 40000000 (gap: 40000000:bffc0000)
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] setup_percpu: NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 28 pages/cpu @ffff88003fc00000 s82880 r8192 d23616 u2097152
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 257894
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.2.0-35-virtual root=UUID=02147f18-c4e2-47d4-ba41-a162651517cb ro console=ttyS0 console=tty0 rootdelay=1800
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] xsave/xrstor: enabled xstate_bv 0x3, cntxt size 0xa88
[    0.000000] Checking aperture...
[    0.000000] No AGP bridge found
[    0.000000] Memory: 1011328k/1048432k available (6540k kernel code, 452k absent, 36652k reserved, 6652k data, 924k init)
[    0.000000] SLUB: Genslabs=15, HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000] 	RCU dyntick-idle grace-period acceleration is enabled.
[    0.000000] NR_IRQS:4352 nr_irqs:256 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty0] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] allocated 8388608 bytes of page_cgroup
[    0.000000] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000000] Fast TSC calibration using PIT
[    0.000000] Detected 3099.919 MHz processor.
[    0.012710] Calibrating delay loop (skipped), value calculated using timer frequency.. 6199.83 BogoMIPS (lpj=12399676)
[    0.016610] pid_max: default: 32768 minimum: 301
[    0.021064] Security Framework initialized
[    0.024787] AppArmor: AppArmor initialized
[    0.025219] Yama: becoming mindful.
[    0.031113] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.033382] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.034818] Mount-cache hash table entries: 256
[    0.044045] Initializing cgroup subsys cpuacct
[    0.044622] Initializing cgroup subsys memory
[    0.045692] Initializing cgroup subsys devices
[    0.046103] Initializing cgroup subsys freezer
[    0.046454] Initializing cgroup subsys blkio
[    0.046817] Initializing cgroup subsys perf_event
[    0.050857] mce: CPU supports 10 MCE banks
[    0.053664] SMP alternatives: switching to UP code
[    0.348411] Freeing SMP alternatives: 24k freed
[    0.349328] ACPI: Core revision 20110623
[    0.375333] ftrace: allocating 27024 entries in 106 pages
[    0.393635] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.434506] CPU0: AMD EPYC Processor stepping 02
[    0.436026] Performance Events: Broken PMU hardware detected, using software events only.
[    0.440367] NMI watchdog disabled (cpu0): hardware events not enabled
[    0.441477] Brought up 1 CPUs
[    0.442128] Total of 1 processors activated (6199.83 BogoMIPS).
[    0.456828] devtmpfs: initialized
[    0.464858] EVM: security.selinux
[    0.465182] EVM: security.SMACK64
[    0.465486] EVM: security.capability
[    0.475757] print_constraints: dummy: 
[    0.476919] RTC time:  6:26:26, date: 02/24/21
[    0.478608] NET: Registered protocol family 16
[    0.483361] Extended Config Space enabled on 0 nodes
[    0.484361] ACPI: bus type pci registered
[    0.487053] PCI: Using configuration type 1 for base access
[    0.487785] PCI: Using configuration type 1 for extended access
[    0.505020] bio: create slab <bio-0> at 0
[    0.507961] ACPI: Added _OSI(Module Device)
[    0.508075] ACPI: Added _OSI(Processor Device)
[    0.508957] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.509483] ACPI: Added _OSI(Processor Aggregator Device)
[    0.533506] ACPI: Interpreter enabled
[    0.533917] ACPI: (supports S0 S3 S4 S5)
[    0.535190] ACPI: Using IOAPIC for interrupt routing
[    0.574551] ACPI: No dock devices found.
[    0.575007] HEST: Table not found.
[    0.575729] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.577646] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.580873] pci_root PNP0A03:00: host bridge window [io  0x0000-0x0cf7]
[    0.581452] pci_root PNP0A03:00: host bridge window [io  0x0d00-0xffff]
[    0.582655] pci_root PNP0A03:00: host bridge window [mem 0x000a0000-0x000bffff]
[    0.583979] pci_root PNP0A03:00: host bridge window [mem 0x40000000-0xfebfffff]
[    0.584063] pci_root PNP0A03:00: host bridge window [mem 0x100000000-0x17fffffff]
[    0.595923] pci 0000:00:01.3: quirk: [io  0x0600-0x063f] claimed by PIIX4 ACPI
[    0.596114] pci 0000:00:01.3: quirk: [io  0x0700-0x070f] claimed by PIIX4 SMB
[    0.954979]  pci0000:00: Requesting ACPI _OSC control (0x1d)
[    0.955565]  pci0000:00: ACPI _OSC request failed (AE_NOT_FOUND), returned control mask: 0x1d
[    0.956059] ACPI _OSC control for PCIe not granted, disabling ASPM
[    0.991908] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[    0.993191] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[    0.994309] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[    0.995372] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[    0.996463] ACPI: PCI Interrupt Link [LNKS] (IRQs *9)
[    1.000602] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    1.001241] vgaarb: loaded
[    1.001489] vgaarb: bridge control possible 0000:00:02.0
[    1.004190] i2c-core: driver [aat2870] using legacy suspend method
[    1.004620] i2c-core: driver [aat2870] using legacy resume method
[    1.006163] SCSI subsystem initialized
[    1.008351] usbcore: registered new interface driver usbfs
[    1.009071] usbcore: registered new interface driver hub
[    1.009831] usbcore: registered new device driver usb
[    1.012233] PCI: Using ACPI for IRQ routing
[    1.019211] NetLabel: Initializing
[    1.019569] NetLabel:  domain hash size = 128
[    1.019934] NetLabel:  protocols = UNLABELED CIPSOv4
[    1.021070] NetLabel:  unlabeled traffic allowed by default
[    1.022821] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0
[    1.023523] hpet0: 3 comparators, 64-bit 100.000000 MHz counter
[    1.028104] Switching to clocksource hpet
[    1.127714] AppArmor: AppArmor Filesystem Enabled
[    1.128952] pnp: PnP ACPI init
[    1.129390] ACPI: bus type pnp registered
[    1.139573] pnp: PnP ACPI: found 10 devices
[    1.140007] ACPI: ACPI bus type pnp unregistered
[    1.170735] NET: Registered protocol family 2
[    1.174793] IP route cache hash table entries: 32768 (order: 6, 262144 bytes)
[    1.180903] TCP established hash table entries: 131072 (order: 9, 2097152 bytes)
[    1.183668] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes)
[    1.185204] TCP: Hash tables configured (established 131072 bind 65536)
[    1.186445] TCP reno registered
[    1.186857] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    1.188016] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    1.189941] NET: Registered protocol family 1
[    1.191770] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    1.192395] pci 0000:00:01.0: PIIX3: Enabling Passive Release
[    1.193628] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    1.196888] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
[    1.197620] pci 0000:00:01.2: PCI INT D -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.199031] pci 0000:00:01.2: PCI INT D disabled
[    1.209655] Trying to unpack rootfs image as initramfs...
[    1.225155] audit: initializing netlink socket (disabled)
[    1.226245] type=2000 audit(1614147986.220:1): initialized
[    1.344590] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    1.385752] VFS: Disk quotas dquot_6.5.2
[    1.386656] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    1.401236] fuse init (API version 7.17)
[    1.402923] msgmni has been set to 1975
[    1.425480] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.432836] io scheduler noop registered
[    1.433313] io scheduler deadline registered (default)
[    1.434149] io scheduler cfq registered
[    1.436693] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    1.438157] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    1.441506] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.442630] ACPI: Power Button [PWRF]
[    1.462907] ERST: Table is not found!
[    1.463353] GHES: HEST is not enabled!
[    1.469245] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 10
[    1.469856] virtio-pci 0000:00:03.0: PCI INT A -> Link[LNKC] -> GSI 10 (level, high) -> IRQ 10
[    1.471967] virtio-pci 0000:00:04.0: PCI INT A -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.481734] ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
[    1.482327] virtio-pci 0000:00:05.0: PCI INT A -> Link[LNKA] -> GSI 10 (level, high) -> IRQ 10
[    1.484407] ACPI: PCI Interrupt Link [LNKB] enabled at IRQ 11
[    1.484935] virtio-pci 0000:00:06.0: PCI INT A -> Link[LNKB] -> GSI 11 (level, high) -> IRQ 11
[    1.487372] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    1.510551] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.585198] 00:05: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.614453] Linux agpgart interface v0.103
[    1.647626] brd: module loaded
[    1.659456] loop: module loaded
[    1.717479]  vda: vda1
[    1.748863] scsi0 : ata_piix
[    1.750567] scsi1 : ata_piix
[    1.751455] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc0e0 irq 14
[    1.752164] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc0e8 irq 15
[    1.757941] Fixed MDIO Bus: probed
[    1.758568] tun: Universal TUN/TAP device driver, 1.6
[    1.759003] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.765368] PPP generic driver version 2.4.2
[    1.776984] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.777828] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.778519] uhci_hcd: USB Universal Host Controller Interface driver
[    1.779261] uhci_hcd 0000:00:01.2: PCI INT D -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.780704] uhci_hcd 0000:00:01.2: UHCI Host Controller
[    1.788702] uhci_hcd 0000:00:01.2: new USB bus registered, assigned bus number 1
[    1.790015] uhci_hcd 0000:00:01.2: irq 11, io base 0x0000c080
[    1.802697] hub 1-0:1.0: USB hub found
[    1.803450] hub 1-0:1.0: 2 ports detected
[    1.806530] usbcore: registered new interface driver libusual
[    1.807630] i8042: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[    1.810836] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.811477] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.825396] mousedev: PS/2 mouse device common for all mice
[    1.828948] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[    1.830689] rtc_cmos 00:01: RTC can wake from S4
[    1.840798] rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
[    1.841864] rtc0: alarms up to one day, y3k, 114 bytes nvram, hpet irqs
[    1.844593] device-mapper: uevent: version 1.0.3
[    1.852584] device-mapper: ioctl: 4.22.0-ioctl (2011-10-19) initialised: dm-devel@redhat.com
[    1.853904] cpuidle: using governor ladder
[    1.854353] cpuidle: using governor menu
[    1.854730] EFI Variables Facility v0.08 2004-May-17
[    1.857252] TCP cubic registered
[    1.858759] NET: Registered protocol family 10
[    1.867095] NET: Registered protocol family 17
[    1.867671] Registering the dns_resolver key type
[    1.885782] registered taskstats version 1
[    1.964623] Freeing initrd memory: 4356k freed
[    2.119960] usb 1-1: new full-speed USB device number 2 using uhci_hcd
[    2.217046] Refined TSC clocksource calibration: 3099.913 MHz.
[    2.218015] Switching to clocksource tsc
[    2.252975]   Magic number: 9:786:418
[    2.254116] rtc_cmos 00:01: setting system clock to 2021-02-24 06:26:28 UTC (1614147988)
[    2.256001] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    2.256624] EDD information not available.
[    2.270404] Freeing unused kernel memory: 924k freed
[    2.285911] Write protecting the kernel read-only data: 12288k
[    2.312630] Freeing unused kernel memory: 1632k freed
[    2.332831] Freeing unused kernel memory: 1200k freed
[    2.986595] udevd[83]: starting version 175
[    6.463393] FDC 0 is a S82078B
[    6.670212] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: (null)
[   13.939792] EXT4-fs (vda1): re-mounted. Opts: (null)

Ubuntu 12.04.1 LTS ctest-vm1-test-48113327 ttyS0

ctest-vm1-test-48113327 login: 
2021-02-24 06:31:49,961 - INFO - Deleting VM ctest-vm1-test-48113327
2021-02-24 06:31:50,409 - INFO - Deleting VN ctest-vn1-vdns-48027156 
2021-02-24 06:31:50,495 - DEBUG - VN c4036f79-8cc5-4ace-aa77-dc04971c9493 still in use: Unable to complete operation on network c4036f79-8cc5-4ace-aa77-dc04971c9493. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-48eb61f9-4de6-401f-8579-9a16f4657858']
2021-02-24 06:31:50,495 - WARNING - Deleting VN ctest-vn1-vdns-48027156 failed..Will retry
2021-02-24 06:31:53,466 - DEBUG - Response for deleting network ()
2021-02-24 06:31:53,567 - DEBUG - Deleting VDNS Entry: ctest-vdns1-68232433
2021-02-24 06:31:53,812 - INFO - VDNS info: ['admin_domain', 'ctest-vdns1-68232433'] deleted successfully.
2021-02-24 06:31:53,812 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:31:53,932 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:31:53,981 - INFO - VDNS information ctest-vdns1-68232433 removed from the API Server
2021-02-24 06:31:54,065 - INFO - VDNS information ctest-vdns1-68232433 removed in the Control node
2021-02-24 06:31:54,065 - DEBUG - Skipping the deletion of Project ['admin_domain', 'ctest-TestvDNSBasic0-54333399']
2021-02-24 06:31:56,090 - ERROR - AssertionError
Python 3.6.8: /usr/bin/python3
Wed Feb 24 06:31:49 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fe59d49c080>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestvDNSBasic0.test_vdns_ping_same_vn>
self = <scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fe59d49c080>
args = ()
kwargs = {}

 /contrail-test/scripts/vdns/test_vdns_basic.py in test_vdns_ping_same_vn(self=<scripts.vdns.test_vdns_basic.TestvDNSBasic0.tes...uite1,vcenter,vcenter_compute] id=0x7fe59d49c080>)
  109                 VMFixture(project_name=self.inputs.project_name, connections=self.connections, vn_obj=vn_quantum_obj, vm_name=vm_name,image_name='ubuntu-traffic'))
  110             assert vm_fixture[vm_name].wait_till_vm_is_up(), ('VM %s'
  111                 ' failed to come up' % (vm_name))
  112             vm_ip = vm_fixture[vm_name].get_vm_ip_from_vm(
  113                 vn_fq_name=vm_fixture[vm_name].vn_fq_name)
vm_name = 'ctest-vm1-test-48113327'
AssertionError: VM ctest-vm1-test-48113327 failed to come up
    __cause__ = None
    __class__ = <class 'AssertionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AssertionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AssertionError object>
    __doc__ = 'Assertion failed.'
    __eq__ = <method-wrapper '__eq__' of AssertionError object>
    __format__ = <built-in method __format__ of AssertionError object>
    __ge__ = <method-wrapper '__ge__' of AssertionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AssertionError object>
    __gt__ = <method-wrapper '__gt__' of AssertionError object>
    __hash__ = <method-wrapper '__hash__' of AssertionError object>
    __init__ = <method-wrapper '__init__' of AssertionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AssertionError object>
    __lt__ = <method-wrapper '__lt__' of AssertionError object>
    __ne__ = <method-wrapper '__ne__' of AssertionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AssertionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AssertionError object>
    __repr__ = <method-wrapper '__repr__' of AssertionError object>
    __setattr__ = <method-wrapper '__setattr__' of AssertionError object>
    __setstate__ = <built-in method __setstate__ of AssertionError object>
    __sizeof__ = <built-in method __sizeof__ of AssertionError object>
    __str__ = <method-wrapper '__str__' of AssertionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('VM ctest-vm1-test-48113327 failed to come up',)
    with_traceback = <built-in method with_traceback of AssertionError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/vdns/test_vdns_basic.py", line 111, in test_vdns_ping_same_vn
    ' failed to come up' % (vm_name))
AssertionError: VM ctest-vm1-test-48113327 failed to come up



2021-02-24 06:31:56,132 - DEBUG - No XMPP flaps were noticed during the test
2021-02-24 06:31:56,132 - INFO - 
2021-02-24 06:31:56,133 - INFO - END TEST : test_vdns_ping_same_vn : FAILED[0:06:11]
2021-02-24 06:31:56,133 - INFO - --------------------------------------------------------------------------------
2021-02-24 06:32:01,436 - INFO - Deleted project: ctest-TestvDNSBasic0-54333399, ID : 387c65ad-8dd7-4aea-9ed1-1d3ccccd9ff9 
