2021-02-22 05:00:08,386 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:00:08,416 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:00:08,844 - INFO - Project ctest-TestBasicPolicyIpv4v6-07334929 not found, creating it
2021-02-22 05:00:09,501 - INFO - Created Project:ctest-TestBasicPolicyIpv4v6-07334929, ID : aed66e73-66a1-4456-85ab-09b2ff6c542a 
2021-02-22 05:00:13,026 - INFO - ================================================================================
2021-02-22 05:00:13,027 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-22 05:00:13,027 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-22 05:00:14,371 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:00:14,372 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:00:14,372 - INFO - 
2021-02-22 05:00:15,805 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'name': 'ctest-vn-54074877', 'admin_state_up': True, 'tenant_id': 'aed66e7366a1445685ab09b2ff6c542a', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': 'aed66e7366a1445685ab09b2ff6c542a', 'id': '7cf34280-9f03-474b-8494-fc2ac0b81438', 'description': ''}}
2021-02-22 05:01:47,152 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:01:45 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7fbb205e0240>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7fbb205e0240>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7fbb205e0240>)
   96         Check that pings fail
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
vn1_fixture undefined
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7fbb205e0240>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7fbb205e0240>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7fbb205e0240>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy.TestBasicPolicyIpv4v6'>, vn_name='ctest-vn-54074877', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-54074877', subnets=[{'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}, {'cidr': '39e4:fcde:477d:b2da:cd1f:b1b7::/96'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-54074877'
subnets = [{'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}, {'cidr': '39e4:fcde:477d:b2da:cd1f:b1b7::/96'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-54074877', vn_subnets=[{'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}, {'cidr': '39e4:fcde:477d:b2da:cd1f:b1b7::/96'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}
net_id = '7cf34280-9f03-474b-8494-fc2ac0b81438'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}, net_id='7cf34280-9f03-474b-8494-fc2ac0b81438', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '115.117.174.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '7cf34280-9f03-474b-8494-fc2ac0b81438'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7fbb1e93d4e0>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "115.117.174.0/26", "network...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '8b27c8811c9e45768abbf6303ba325d5'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 98, in test_basic_policy_allow_deny
    vn1_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:01:47,201 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:01:47,202 - INFO - 
2021-02-22 05:01:47,202 - INFO - END TEST : test_basic_policy_allow_deny : FAILED[0:01:34]
2021-02-22 05:01:47,202 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:01:47,337 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:01:49,455 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:01:51,581 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:01:53,703 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:01:55,827 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:01:57,938 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:00,056 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:02,175 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:04,301 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:06,424 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:08,535 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:10,686 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:12,798 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:14,915 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:17,038 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:19,142 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:21,263 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:23,393 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:25,529 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:27,643 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:29,762 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:31,889 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:34,006 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:36,106 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:38,249 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:40,376 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:42,501 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:44,634 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:46,758 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:48,873 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:50,998 - WARNING - Project ctest-TestBasicPolicyIpv4v6-07334929 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-07334929', 'ctest-vn-54074877'], 'href': 'https://192.168.7.34:8082/virtual-network/7cf34280-9f03-474b-8494-fc2ac0b81438', 'uuid': '7cf34280-9f03-474b-8494-fc2ac0b81438'}] before deletion
2021-02-22 05:02:50,999 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicyIpv4v6-07334929
2021-02-22 05:23:26,095 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-22 05:23:26,134 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-22 05:23:27,476 - INFO - Project ctest-TestBasicPolicyIpv4v6-39290383 not found, creating it
2021-02-22 05:23:28,176 - INFO - Created Project:ctest-TestBasicPolicyIpv4v6-39290383, ID : 470b87f6-4c1d-4afc-8198-cc61204fd676 
2021-02-22 05:23:32,781 - INFO - ================================================================================
2021-02-22 05:23:32,782 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-22 05:23:32,782 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-22 05:23:34,131 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-22 05:23:34,132 - INFO - Initial checks done. Running the testcase now
2021-02-22 05:23:34,132 - INFO - 
2021-02-22 05:23:35,209 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'name': 'ctest-vn-66379919', 'admin_state_up': True, 'tenant_id': '470b87f64c1d4afc8198cc61204fd676', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '470b87f64c1d4afc8198cc61204fd676', 'id': 'ea3679e8-d926-4712-98cc-2447898dbc88', 'description': ''}}
2021-02-22 05:23:35,558 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88', 'tenant_id': '470b87f64c1d4afc8198cc61204fd676', 'created_at': '2021-02-22T05:23:34.925361', 'dns_nameservers': [], 'updated_at': '2021-02-22T05:23:34.925361', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '122.135.149.2', 'end': '122.135.149.62'}], 'gateway_ip': '122.135.149.1', 'dns_server_address': '122.135.149.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '122.135.149.0/26', 'id': '02d4f67a-2c62-4120-8f4d-2e09c3f0a3e8'}}
2021-02-22 05:25:06,932 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Mon Feb 22 05:25:05 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f099ddbff98>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f099ddbff98>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f099ddbff98>)
   96         Check that pings fail
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
vn1_fixture undefined
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f099ddbff98>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7f099ddbff98>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f099ddbff98>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy.TestBasicPolicyIpv4v6'>, vn_name='ctest-vn-66379919', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-66379919', subnets=[{'cidr': '122.135.149.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}, {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-66379919'
subnets = [{'cidr': '122.135.149.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}, {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-66379919', vn_subnets=[{'cidr': '122.135.149.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}, {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}
net_id = 'ea3679e8-d926-4712-98cc-2447898dbc88'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}, net_id='ea3679e8-d926-4712-98cc-2447898dbc88', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '2b5e:ca41:7d4f:2fd0:8282:bd79::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': 'ea3679e8-d926-4712-98cc-2447898dbc88'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f099da00dd8>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "2b5e:ca41:7d4f:2fd0:8282:bd...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '841d64e621c0422bbdaccf12d1660813'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 98, in test_basic_policy_allow_deny
    vn1_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-22 05:25:06,975 - DEBUG - No XMPP flaps were noticed during the test
2021-02-22 05:25:06,975 - INFO - 
2021-02-22 05:25:06,976 - INFO - END TEST : test_basic_policy_allow_deny : FAILED[0:01:34]
2021-02-22 05:25:06,976 - INFO - --------------------------------------------------------------------------------
2021-02-22 05:25:07,126 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:09,228 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:11,342 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:13,452 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:15,554 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:17,659 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:19,779 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:21,897 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:24,008 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:26,129 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:28,241 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:30,409 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:32,515 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:34,624 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:36,731 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:38,835 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:40,943 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:43,062 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:45,177 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:47,293 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:49,405 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:51,511 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:53,627 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:55,745 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:57,843 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:25:59,959 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:02,078 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:04,200 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:06,337 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:08,448 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:10,573 - WARNING - Project ctest-TestBasicPolicyIpv4v6-39290383 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-39290383', 'ctest-vn-66379919'], 'href': 'https://192.168.7.34:8082/virtual-network/ea3679e8-d926-4712-98cc-2447898dbc88', 'uuid': 'ea3679e8-d926-4712-98cc-2447898dbc88'}] before deletion
2021-02-22 05:26:10,574 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicyIpv4v6-39290383
2021-02-23 05:53:02,302 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-23 05:53:04,103 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-23 05:53:04,935 - INFO - Project ctest-TestBasicPolicyIpv4v6-05944321 not found, creating it
2021-02-23 05:53:06,109 - INFO - Created Project:ctest-TestBasicPolicyIpv4v6-05944321, ID : 0c95ad96-2033-4188-bf6d-6fe984ab769c 
2021-02-23 05:53:10,424 - INFO - ================================================================================
2021-02-23 05:53:10,424 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-23 05:53:10,425 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-23 05:53:10,720 - ERROR - [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/contrail-test/tcutils/cores.py", line 47, in get_cores_node
    if exists(CORE_DIR):
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 31, in exists
    cmd = 'stat %s' % _expand_path(path)
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 485, in _expand_path
    return path if is_win() else '"$(echo %s)"' % path
  File "/usr/local/lib64/python3.6/site-packages/fabric/contrib/files.py", line 472, in is_win
    return '"' in run('echo "Will you echo quotation marks"')
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 1095, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 420, in _open_session
    session = transport.open_session(timeout=env.timeout)
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 879, in open_session
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1006, in open_channel
    raise e
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 301, in read_all
    x = self.__socket.recv(n)
  File "/usr/local/lib64/python3.6/site-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-02-23 05:53:11,529 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-23 05:53:11,529 - INFO - Initial checks done. Running the testcase now
2021-02-23 05:53:11,529 - INFO - 
2021-02-23 05:53:13,325 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'name': 'ctest-vn-98152639', 'admin_state_up': True, 'tenant_id': '0c95ad9620334188bf6d6fe984ab769c', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '0c95ad9620334188bf6d6fe984ab769c', 'id': '710e2819-0050-4678-9c5a-99960e49a225', 'description': ''}}
2021-02-23 05:53:13,726 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '710e2819-0050-4678-9c5a-99960e49a225', 'tenant_id': '0c95ad9620334188bf6d6fe984ab769c', 'created_at': '2021-02-23T05:53:12.917183', 'dns_nameservers': [], 'updated_at': '2021-02-23T05:53:12.917183', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '51.243.50.2', 'end': '51.243.50.62'}], 'gateway_ip': '51.243.50.1', 'dns_server_address': '51.243.50.2', 'ipv6_address_mode': None, 'ip_version': 4, 'host_routes': [], 'cidr': '51.243.50.0/26', 'id': '0bffa1d3-eb8c-4423-988a-93a3f5907e49'}}
2021-02-23 05:54:46,012 - ERROR - ConnectFailure
Python 3.6.8: /usr/bin/python3
Tue Feb 23 05:54:43 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /contrail-test/tcutils/wrappers.py in wrapper(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f3359208ef0>, *args=(), **kwargs={})
   80             log.info('Initial checks done. Running the testcase now')
   81             log.info('')
   82             result = function(self, *args, **kwargs)
   83             if self.inputs.upgrade:
   84                 pid = os.getpid()
result = None
function = <function TestBasicPolicy.test_basic_policy_allow_deny>
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f3359208ef0>
args = ()
kwargs = {}

 /contrail-test/scripts/policy/test_policy_basic.py in test_basic_policy_allow_deny(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f3359208ef0>)
   96         Check that pings fail
   97         '''
   98         vn1_fixture = self.create_vn()
   99         vn2_fixture = self.create_vn()
  100 #        vn1_name = get_random_name('vn1')
vn1_fixture undefined
self = <scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f3359208ef0>
self.create_vn = <bound method GenericTestBase.create_vn of <scri...anity,suite1,vcenter_compute] id=0x7f3359208ef0>>

 /contrail-test/common/base.py in create_vn(self=<scripts.policy.test_policy.TestBasicPolicyIpv4v...sanity,suite1,vcenter_compute] id=0x7f3359208ef0>, vn_name=None, vn_subnets=None, cleanup=True, **kwargs={})
  202         vn_fixture = self.create_only_vn(vn_name=vn_name,
  203                                      vn_subnets=vn_subnets,
  204                                      **kwargs)
  205         if cleanup:
  206             self.addCleanup(vn_fixture.cleanUp)
kwargs = {}

 /contrail-test/common/base.py in create_only_vn(cls=<class 'scripts.policy.test_policy.TestBasicPolicyIpv4v6'>, vn_name='ctest-vn-98152639', vn_subnets=None, **kwargs={})
  195                       subnets=vn_subnets,
  196                       **kwargs)
  197         vn_fixture.setUp()
  198         return vn_fixture
  199     # end create_only_vn
vn_fixture = <vn_test.VNFixture object>
vn_fixture.setUp = <bound method VNFixture.setUp of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in setUp(self=<vn_test.VNFixture object>)
  442     def setUp(self):
  443         super(VNFixture, self).setUp()
  444         self.create()
  445 
  446     def create(self):
self = <vn_test.VNFixture object>
self.create = <bound method VNFixture.create of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in create(self=<vn_test.VNFixture object>)
  455             self._create_vn_api(self.vn_name, self.project_obj)
  456         else:
  457             self._create_vn_orch()
  458         if not self.obj:
  459              self.logger.debug('VN %s not present' % (self.vn_name))
self = <vn_test.VNFixture object>
self._create_vn_orch = <bound method VNFixture._create_vn_orch of <vn_test.VNFixture object>>

 /contrail-test/fixtures/vn_test.py in _create_vn_orch(self=<vn_test.VNFixture object>)
  313                                                 sriov_provider_network=self.sriov_provider_network,
  314                                                 disable_gateway=self.disable_gateway,
  315                                                 dns_nameservers_list=self.dns_nameservers_list)
  316                 if self.obj:
  317                     self.logger.info('Created VN %s' %(self.vn_name))
dns_nameservers_list undefined
self = <vn_test.VNFixture object>
self.dns_nameservers_list = None

 /contrail-test/fixtures/openstack.py in create_vn(self=<openstack.OpenstackOrchestrator object>, name='ctest-vn-98152639', subnets=[{'cidr': '51.243.50.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}, {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}], option='orch', **kwargs={'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None})
  184 
  185    def create_vn(self, name, subnets, option='orch', **kwargs):
  186        return self.quantum_h.create_network(name, subnets, **kwargs)
  187 
  188    def delete_vn(self, vn_obj, option='orch', **kwargs):
self = <openstack.OpenstackOrchestrator object>
self.quantum_h = <quantum_test.QuantumHelper object>
self.quantum_h.create_network = <bound method QuantumHelper.create_network of <quantum_test.QuantumHelper object>>
name = 'ctest-vn-98152639'
subnets = [{'cidr': '51.243.50.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}, {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}]
kwargs = {'disable_gateway': False, 'dns_nameservers_list': None, 'enable_dhcp': True, 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'router_external': False, 'shared': False, 'sriov_enable': False, 'sriov_provider_network': None, 'sriov_vlan': None}

 /contrail-test/fixtures/quantum_test.py in create_network(self=<quantum_test.QuantumHelper object>, vn_name='ctest-vn-98152639', vn_subnets=[{'cidr': '51.243.50.0/26', 'enable_dhcp': True, 'ip_version': '4', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}, {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}], ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], shared=False, router_external=False, enable_dhcp=True, sriov_enable=False, sriov_vlan=None, sriov_provider_network=None, dns_nameservers_list=None, disable_gateway=False)
  107                 for subnet in vn_subnets:
  108                     net_rsp = self.create_subnet(
  109                         subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  110             # end for
  111             return self.obj.show_network(network=net_id)
subnet = {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}
net_id = '710e2819-0050-4678-9c5a-99960e49a225'
ipam_fq_name = ['default-domain', 'default-project', 'default-network-ipam']
enable_dhcp = True
disable_gateway = False
dns_nameservers_list = None

 /contrail-test/fixtures/quantum_test.py in create_subnet(self=<quantum_test.QuantumHelper object>, subnet={'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}, net_id='710e2819-0050-4678-9c5a-99960e49a225', ipam_fq_name=['default-domain', 'default-project', 'default-network-ipam'], enable_dhcp=True, disable_gateway=False, dns_nameservers_list=None)
  127            subnet_req['gateway_ip'] = None
  128         try:
  129             subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  130             self.logger.debug(
  131                 'Response for create_subnet : ' +
subnet_rsp undefined
self = <quantum_test.QuantumHelper object>
self.obj = <neutronclient.v2_0.client.Client object>
self.obj.create_subnet = <bound method Client.create_subnet of <neutronclient.v2_0.client.Client object>>
subnet_req = {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in create_subnet(self=<neutronclient.v2_0.client.Client object>, body={'subnet': {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}})
  846     def create_subnet(self, body=None):
  847         """Creates a new subnet."""
  848         return self.post(self.subnets_path, body=body)
  849 
  850     def update_subnet(self, subnet, body=None, revision_number=None):
self = <neutronclient.v2_0.client.Client object>
self.post = <bound method ClientBase.post of <neutronclient.v2_0.client.Client object>>
self.subnets_path = '/subnets'
body = {'subnet': {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}}

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in post(self=<neutronclient.v2_0.client.Client object>, action='/subnets', body={'subnet': {'cidr': '36ed:4e12:7b12:cad1:deba:30bf::/96', 'enable_dhcp': True, 'ip_version': '6', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam'], 'network_id': '710e2819-0050-4678-9c5a-99960e49a225'}}, headers=None, params=None)
  357         # Do not retry POST requests to avoid the orphan objects problem.
  358         return self.do_request("POST", action, body=body,
  359                                headers=headers, params=params)
  360 
  361     def put(self, action, body=None, headers=None, params=None):
headers = None
params = None

 /usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py in do_request(self=<neutronclient.v2_0.client.Client object>, method='POST', action='/v2.0/subnets', body='{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', headers=None, params=None)
  280 
  281         resp, replybody = self.httpclient.do_request(action, method, body=body,
  282                                                      headers=headers)
  283 
  284         status_code = resp.status_code
headers = None

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in do_request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'body': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': None})
  338         kwargs.setdefault('authenticated', True)
  339         self._check_uri_length(url)
  340         return self.request(url, method, **kwargs)
  341 
  342     @property
self = <neutronclient.client.SessionClient object>
self.request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'body': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': None}

 /usr/local/lib/python3.6/site-packages/neutronclient/client.py in request(self=<neutronclient.client.SessionClient object>, *args=('/v2.0/subnets', 'POST'), **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'raise_exc': False})
  326 
  327         kwargs['headers'] = headers
  328         resp = super(SessionClient, self).request(*args, **kwargs)
  329         return resp, resp.text
  330 
resp undefined
builtinsuper = <class 'super'>
global SessionClient = <class 'neutronclient.client.SessionClient'>
self = <neutronclient.client.SessionClient object>
).request = <bound method SessionClient.request of <neutronclient.client.SessionClient object>>
args = ('/v2.0/subnets', 'POST')
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'raise_exc': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py in request(self=<neutronclient.client.SessionClient object>, url='/v2.0/subnets', method='POST', **kwargs={'authenticated': True, 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'})
  246             kwargs.setdefault('raise_exc', self.raise_exc)
  247 
  248         return self.session.request(url, method, **kwargs)
  249 
  250     def get_token(self, auth=None):
self = <neutronclient.client.SessionClient object>
self.session = <keystoneauth1.session.Session object>
self.session.request = <bound method Session.request of <keystoneauth1.session.Session object>>
url = '/v2.0/subnets'
method = 'POST'
kwargs = {'authenticated': True, 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'endpoint_filter': {'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'raise_exc': False, 'rate_semaphore': <keystoneauth1._fair_semaphore.FairSemaphore object>, 'user_agent': 'python-neutronclient'}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', json=None, original_ip=None, user_agent='python-neutronclient', redirect=30, authenticated=True, endpoint_filter={'interface': 'public', 'region_name': 'RegionOne', 'service_type': 'network'}, auth=None, requests_auth=None, raise_exc=False, allow_reauth=True, log=True, endpoint_override=None, connect_retries=0, logger=<Logger keystoneauth.session (WARNING)>, allow=None, client_name=None, client_version=None, microversion=None, microversion_service_type=None, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, global_request_id=None, connect_retry_delay=None, status_code_retry_delay=None, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'verify': False})
  911                 kwargs.update(connection_params)
  912 
  913         resp = send(**kwargs)
  914 
  915         # log callee and caller request-id for each api call
resp undefined
send = functools.partial(<bound method Session._send_re...auth1.session._Retries object at 0x7f3353958e10>)
kwargs = {'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'verify': False}

 /usr/local/lib/python3.6/site-packages/keystoneauth1/session.py in _send_request(self=<keystoneauth1.session.Session object>, url='http://192.168.7.31:9696/v2.0/subnets', method='POST', redirect=30, log=True, logger=<Logger keystoneauth.session (WARNING)>, split_loggers=None, connect_retries=0, status_code_retries=0, retriable_status_codes=[503], rate_semaphore=<keystoneauth1._fair_semaphore.FairSemaphore object>, connect_retry_delays=<keystoneauth1.session._Retries object>, status_code_retry_delays=<keystoneauth1.session._Retries object>, **kwargs={'allow_redirects': False, 'cert': (None, None), 'data': '{"subnet": {"cidr": "36ed:4e12:7b12:cad1:deba:30...in", "default-project", "default-network-ipam"]}}', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'python-neutronclient', 'X-Auth-Token': '39d38d19429740a987f0264d7b864fb5'}, 'verify': False})
 1018                 # and firewall blocking.
 1019                 msg = 'Unable to establish connection to %s: %s' % (url, e)
 1020                 raise exceptions.ConnectFailure(msg)
 1021             except requests.exceptions.RequestException as e:
 1022                 msg = 'Unexpected exception for %(url)s: %(error)s' % {
global exceptions = <module 'keystoneauth1.exceptions' from '/usr/lo...e-packages/keystoneauth1/exceptions/__init__.py'>
exceptions.ConnectFailure = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
msg = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    __cause__ = None
    __class__ = <class 'keystoneauth1.exceptions.connection.ConnectFailure'>
    __context__ = ConnectionError(ProtocolError('Connection aborte...mote end closed connection without response',)),)
    __delattr__ = <method-wrapper '__delattr__' of ConnectFailure object>
    __dict__ = {'message': "Unable to establish connection to http://192.168...Remote end closed connection without response',))"}
    __dir__ = <built-in method __dir__ of ConnectFailure object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of ConnectFailure object>
    __format__ = <built-in method __format__ of ConnectFailure object>
    __ge__ = <method-wrapper '__ge__' of ConnectFailure object>
    __getattribute__ = <method-wrapper '__getattribute__' of ConnectFailure object>
    __gt__ = <method-wrapper '__gt__' of ConnectFailure object>
    __hash__ = <method-wrapper '__hash__' of ConnectFailure object>
    __init__ = <bound method ClientException.__init__ of Connec...te end closed connection without response',))",)>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ConnectFailure object>
    __lt__ = <method-wrapper '__lt__' of ConnectFailure object>
    __module__ = 'keystoneauth1.exceptions.connection'
    __ne__ = <method-wrapper '__ne__' of ConnectFailure object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ConnectFailure object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ConnectFailure object>
    __repr__ = <method-wrapper '__repr__' of ConnectFailure object>
    __setattr__ = <method-wrapper '__setattr__' of ConnectFailure object>
    __setstate__ = <built-in method __setstate__ of ConnectFailure object>
    __sizeof__ = <built-in method __sizeof__ of ConnectFailure object>
    __str__ = <method-wrapper '__str__' of ConnectFailure object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ("Unable to establish connection to http://192.168...Remote end closed connection without response',))",)
    message = "Unable to establish connection to http://192.168...Remote end closed connection without response',))"
    with_traceback = <built-in method with_traceback of ConnectFailure object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1004, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/contrail-test/tcutils/wrappers.py", line 82, in wrapper
    result = function(self, *args, **kwargs)
  File "/contrail-test/scripts/policy/test_policy_basic.py", line 98, in test_basic_policy_allow_deny
    vn1_fixture = self.create_vn()
  File "/contrail-test/common/base.py", line 204, in create_vn
    **kwargs)
  File "/contrail-test/common/base.py", line 197, in create_only_vn
    vn_fixture.setUp()
  File "/contrail-test/fixtures/vn_test.py", line 444, in setUp
    self.create()
  File "/contrail-test/fixtures/vn_test.py", line 457, in create
    self._create_vn_orch()
  File "/contrail-test/fixtures/vn_test.py", line 315, in _create_vn_orch
    dns_nameservers_list=self.dns_nameservers_list)
  File "/contrail-test/fixtures/openstack.py", line 186, in create_vn
    return self.quantum_h.create_network(name, subnets, **kwargs)
  File "/contrail-test/fixtures/quantum_test.py", line 109, in create_network
    subnet, net_id, ipam_fq_name, enable_dhcp, disable_gateway,dns_nameservers_list)
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 282, in do_request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 340, in do_request
    return self.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/client.py", line 328, in request
    resp = super(SessionClient, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 913, in request
    resp = send(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/keystoneauth1/session.py", line 1020, in _send_request
    raise exceptions.ConnectFailure(msg)
keystoneauth1.exceptions.connection.ConnectFailure: Unable to establish connection to http://192.168.7.31:9696/v2.0/subnets: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))



2021-02-23 05:54:46,060 - DEBUG - No XMPP flaps were noticed during the test
2021-02-23 05:54:46,060 - INFO - 
2021-02-23 05:54:46,060 - INFO - END TEST : test_basic_policy_allow_deny : FAILED[0:01:36]
2021-02-23 05:54:46,060 - INFO - --------------------------------------------------------------------------------
2021-02-23 05:54:46,202 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:48,329 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:50,449 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:52,581 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:54,707 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:56,825 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:54:58,942 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:01,066 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:03,183 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:05,287 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:07,403 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:09,519 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:11,645 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:13,771 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:15,884 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:17,986 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:20,104 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:22,210 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:24,320 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:26,425 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:28,541 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:30,664 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:32,803 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:34,938 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:37,066 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:39,164 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:41,273 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:43,378 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:45,517 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:47,632 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:49,755 - WARNING - Project ctest-TestBasicPolicyIpv4v6-05944321 still has VNs [{'to': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-05944321', 'ctest-vn-98152639'], 'href': 'https://192.168.7.34:8082/virtual-network/710e2819-0050-4678-9c5a-99960e49a225', 'uuid': '710e2819-0050-4678-9c5a-99960e49a225'}] before deletion
2021-02-23 05:55:49,756 - WARNING - One or more references still present, will not delete the project ctest-TestBasicPolicyIpv4v6-05944321
2021-02-24 06:22:31,486 - INFO - Reading existing Domain with UUID f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:31,519 - INFO - Using existing domain ['admin_domain'](f27c063f-c6c4-434f-a616-97e72e0043e5)
2021-02-24 06:22:34,490 - INFO - Project ctest-TestBasicPolicyIpv4v6-66950153 not found, creating it
2021-02-24 06:22:35,410 - INFO - Created Project:ctest-TestBasicPolicyIpv4v6-66950153, ID : 5acb2f8a-134d-4ee0-923f-daa914c96c94 
2021-02-24 06:22:44,008 - INFO - ================================================================================
2021-02-24 06:22:44,008 - INFO - STARTING TEST    : test_basic_policy_allow_deny
2021-02-24 06:22:44,008 - INFO - TEST DESCRIPTION : 
        Create 2 Vns and allow icmp traffic between them and validate with pings
        Update the policy to deny the same traffic
        Check that pings fail
        
2021-02-24 06:22:45,340 - DEBUG - Nothing to compare xmpp stats {'192.168.7.19': {'192.168.27.20': '0', '192.168.27.34': '0'}, '192.168.7.9': {'192.168.27.20': '0', '192.168.27.34': '0'}} with
2021-02-24 06:22:45,340 - INFO - Initial checks done. Running the testcase now
2021-02-24 06:22:45,340 - INFO - 
2021-02-24 06:22:47,012 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-vn-26209205'], 'name': 'ctest-vn-26209205', 'admin_state_up': True, 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'id': '9a9cb9d9-81c2-4728-ae19-901ebffac828', 'description': ''}}
2021-02-24 06:22:47,345 - ERROR - Neutron Exception while creating subnet for vn with id 9a9cb9d9-81c2-4728-ae19-901ebffac828
Traceback (most recent call last):
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
neutronclient.common.exceptions.InternalServerError: The server has either erred or is incapable of performing the requested operation.<br /><br />



Neutron server returns request_ids: ['req-f50abc07-15cb-4121-90f5-6ce791fabe29']
2021-02-24 06:22:47,640 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '9a9cb9d9-81c2-4728-ae19-901ebffac828', 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': '2021-02-24T06:22:46.676117', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:22:46.676117', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '37e7:853a:d18f:7e98:8cbc:9244:0:2', 'end': '37e7:853a:d18f:7e98:8cbc:9244:ffff:fffe'}], 'gateway_ip': '37e7:853a:d18f:7e98:8cbc:9244:0:1', 'dns_server_address': '37e7:853a:d18f:7e98:8cbc:9244:0:2', 'ipv6_address_mode': None, 'ip_version': 6, 'host_routes': [], 'cidr': '37e7:853a:d18f:7e98:8cbc:9244::/96', 'id': '5ad49286-1fe1-4241-b266-0e7073444d21'}}
2021-02-24 06:22:47,691 - INFO - Created VN ctest-vn-26209205
2021-02-24 06:22:47,717 - DEBUG - VN ctest-vn-26209205 UUID is 9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:48,167 - DEBUG - Response for create_network : {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': [], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-vn-45056538'], 'name': 'ctest-vn-45056538', 'admin_state_up': True, 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': None, 'updated_at': None, 'shared': False, 'port_security_enabled': True, 'project_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'id': '4939ebe2-0290-4f2b-bc05-58e3a8f9b80d', 'description': ''}}
2021-02-24 06:22:48,491 - ERROR - Neutron Exception while creating subnet for vn with id 4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
Traceback (most recent call last):
  File "/contrail-test/fixtures/quantum_test.py", line 129, in create_subnet
    subnet_rsp = self.obj.create_subnet({'subnet': subnet_req})
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 848, in create_subnet
    return self.post(self.subnets_path, body=body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 359, in post
    headers=headers, params=params)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 294, in do_request
    self._handle_fault_response(status_code, replybody, resp)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 269, in _handle_fault_response
    exception_handler_v20(status_code, error_body)
  File "/usr/local/lib/python3.6/site-packages/neutronclient/v2_0/client.py", line 93, in exception_handler_v20
    request_ids=request_ids)
neutronclient.common.exceptions.InternalServerError: The server has either erred or is incapable of performing the requested operation.<br /><br />



Neutron server returns request_ids: ['req-d3cba244-76da-495d-8be6-17f73835b779']
2021-02-24 06:22:48,806 - DEBUG - Response for create_subnet : {'subnet': {'name': '', 'enable_dhcp': True, 'network_id': '4939ebe2-0290-4f2b-bc05-58e3a8f9b80d', 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': '2021-02-24T06:22:47.858006', 'dns_nameservers': [], 'updated_at': '2021-02-24T06:22:47.858006', 'ipv6_ra_mode': None, 'allocation_pools': [{'start': '3b39:a02a:e004:78b1:4565:280c:0:2', 'end': '3b39:a02a:e004:78b1:4565:280c:ffff:fffe'}], 'gateway_ip': '3b39:a02a:e004:78b1:4565:280c:0:1', 'dns_server_address': '3b39:a02a:e004:78b1:4565:280c:0:2', 'ipv6_address_mode': None, 'ip_version': 6, 'host_routes': [], 'cidr': '3b39:a02a:e004:78b1:4565:280c::/96', 'id': 'df28ac4f-57bb-460a-8063-d87902d7e42e'}}
2021-02-24 06:22:48,863 - INFO - Created VN ctest-vn-45056538
2021-02-24 06:22:48,897 - DEBUG - VN ctest-vn-45056538 UUID is 4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:49,149 - DEBUG - Policy np_rules : [rule_sequence = None, rule_uuid = None, direction = <>, protocol = icmp, src_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205, security_group = None, network_policy = None, subnet_list = []], src_ports = [start_port = -1, end_port = -1], application = [], dst_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538, security_group = None, network_policy = None, subnet_list = []], dst_ports = [start_port = -1, end_port = -1], action_list = simple_action = pass, gateway_name = None, apply_service = [], service_properties = None, mirror_to = None, assign_routing_instance = None, log = False, alert = False, qos_action = None, host_based_service = False, ethertype = None, created = None, last_modified = None, rule_sequence = None, rule_uuid = None, direction = <>, protocol = 58, src_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205, security_group = None, network_policy = None, subnet_list = []], src_ports = [start_port = -1, end_port = -1], application = [], dst_addresses = [subnet = None, virtual_network = admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538, security_group = None, network_policy = None, subnet_list = []], dst_ports = [start_port = -1, end_port = -1], action_list = simple_action = pass, gateway_name = None, apply_service = [], service_properties = None, mirror_to = None, assign_routing_instance = None, log = False, alert = False, qos_action = None, host_based_service = False, ethertype = None, created = None, last_modified = None]
2021-02-24 06:22:49,478 - DEBUG - Response for mapping policy(s) with vn {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': ['c6aa2165-c42b-45f5-a3d6-e9af5bc26219', '5ad49286-1fe1-4241-b266-0e7073444d21'], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-vn-26209205'], 'name': 'ctest-vn-26209205', 'admin_state_up': True, 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': '2021-02-24T06:22:48.546224', 'updated_at': '2021-02-24T06:22:48.546224', 'policys': [['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-policy-allow-all-89240486']], 'shared': False, 'port_security_enabled': True, 'project_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'subnet_ipam': [{'subnet_cidr': '151.220.74.192/26', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}, {'subnet_cidr': '37e7:853a:d18f:7e98:8cbc:9244::/96', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}], 'id': '9a9cb9d9-81c2-4728-ae19-901ebffac828', 'description': ''}}
2021-02-24 06:22:49,751 - DEBUG - Response for mapping policy(s) with vn {'network': {'status': 'ACTIVE', 'router:external': False, 'subnets': ['bbab466d-2e77-41a7-9478-997effe9c0f7', 'df28ac4f-57bb-460a-8063-d87902d7e42e'], 'fq_name': ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-vn-45056538'], 'name': 'ctest-vn-45056538', 'admin_state_up': True, 'tenant_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'created_at': '2021-02-24T06:22:47.304282', 'updated_at': '2021-02-24T06:22:47.896697', 'policys': [['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-policy-allow-all-89240486']], 'shared': False, 'port_security_enabled': True, 'project_id': '5acb2f8a134d4ee0923fdaa914c96c94', 'subnet_ipam': [{'subnet_cidr': '66.84.199.192/26', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}, {'subnet_cidr': '3b39:a02a:e004:78b1:4565:280c::/96', 'ipam_fq_name': ['default-domain', 'default-project', 'default-network-ipam']}], 'id': '4939ebe2-0290-4f2b-bc05-58e3a8f9b80d', 'description': ''}}
2021-02-24 06:22:49,904 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:50,496 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:50,582 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:50,622 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:22:50,691 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:50,729 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:50,761 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:22:50,792 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:22:50,817 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/57884c12-ee0f-4f57-9b4e-e94fd373da72
2021-02-24 06:22:50,840 - DEBUG - Route Targets: ['target:64512:8000037']
2021-02-24 06:22:50,840 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:50,870 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:22:50,916 - INFO - Verified VN network id 14 for VN 9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:50,917 - INFO - Verifications in API Server for VN ctest-vn-26209205 passed
2021-02-24 06:22:50,917 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:50,947 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:22:50,972 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:22:50,998 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/57884c12-ee0f-4f57-9b4e-e94fd373da72
2021-02-24 06:22:51,038 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '11140983922043799336', 'uuid-lslong': '12545216698761529384'}, 'enable': 'true', 'created': '2021-02-24T06:22:48', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.596214'}
2021-02-24 06:22:51,058 - DEBUG - Route Targets: ['target:64512:8000037']
2021-02-24 06:22:51,155 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '11140983922043799336', 'uuid-lslong': '12545216698761529384'}, 'enable': 'true', 'created': '2021-02-24T06:22:48', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.712523'}
2021-02-24 06:22:51,260 - DEBUG - Route Targets: ['target:64512:8000037']
2021-02-24 06:22:51,277 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '11140983922043799336', 'uuid-lslong': '12545216698761529384'}, 'enable': 'true', 'created': '2021-02-24T06:22:48', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:01.835782'}
2021-02-24 06:22:51,298 - DEBUG - Route Targets: ['target:64512:8000037']
2021-02-24 06:22:51,298 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-vn-26209205 passed
2021-02-24 06:22:51,299 - DEBUG - ====Verifying policy data for ctest-vn-26209205 in API_Server ======
2021-02-24 06:22:51,299 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:51,323 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:51,375 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:22:51,446 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/9a9cb9d9-81c2-4728-ae19-901ebffac828
2021-02-24 06:22:51,479 - DEBUG - ==>Verifying data for policy with id: 2ad1e605-c616-4d44-ac83-424f8cdbddd0, fqn: ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-policy-allow-all-89240486']
2021-02-24 06:22:51,479 - INFO - VN ctest-vn-26209205 Policy verification: verify_vn_policy_in_api_server, status: True
2021-02-24 06:22:51,479 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:51,479 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:51,480 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:53,975 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:54,207 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205'}
2021-02-24 06:22:54,207 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:54,207 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:54,899 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:55,044 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205'}
2021-02-24 06:22:55,045 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:55,045 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:55,643 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:55,854 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205'}
2021-02-24 06:22:55,854 - INFO - Validated that VN admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is found in opserver
2021-02-24 06:22:56,089 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:56,204 - DEBUG - VRF ids for VN ctest-vn-26209205: {}
2021-02-24 06:22:56,205 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:56,236 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:56,303 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:22:56,383 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:56,426 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:56,467 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:22:56,505 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:22:56,540 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/20b43cf3-1d11-4dc3-962f-aaf433cba486
2021-02-24 06:22:56,579 - DEBUG - Route Targets: ['target:64512:8000039']
2021-02-24 06:22:56,579 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:56,624 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:22:56,690 - INFO - Verified VN network id 49 for VN 4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:56,691 - INFO - Verifications in API Server for VN ctest-vn-45056538 passed
2021-02-24 06:22:56,691 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:56,735 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:22:56,777 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:22:56,816 - DEBUG - Requesting: https://192.168.7.20:8082/route-target/20b43cf3-1d11-4dc3-962f-aaf433cba486
2021-02-24 06:22:56,880 - DEBUG - Control-node 192.168.7.20 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '5276507794379394859', 'uuid-lslong': '13548332788829763597'}, 'enable': 'true', 'created': '2021-02-24T06:22:47', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:07.172964'}
2021-02-24 06:22:56,905 - DEBUG - Route Targets: ['target:64512:8000039']
2021-02-24 06:22:56,925 - DEBUG - Control-node 192.168.7.29 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '5276507794379394859', 'uuid-lslong': '13548332788829763597'}, 'enable': 'true', 'created': '2021-02-24T06:22:47', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:07.219966'}
2021-02-24 06:22:56,949 - DEBUG - Route Targets: ['target:64512:8000039']
2021-02-24 06:22:56,970 - DEBUG - Control-node 192.168.7.34 : VN object is : {'node_name': 'virtual-network:admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538', 'interests': '-', 'advertised': '-', 'dbentryflags': None, 'obj_info': {'sequence_number': '0', 'origin': 'Cassandra', 'data': {'id-perms': {'permissions': {'owner': 'ctest-TestBasicPolicyIpv4v6-66950153', 'owner-access': '7', 'group': 'admin', 'group-access': '7', 'other-access': '7'}, 'uuid': {'uuid-mslong': '5276507794379394859', 'uuid-lslong': '13548332788829763597'}, 'enable': 'true', 'created': '2021-02-24T06:22:47', 'last-modified': '2021-02-24T06:22:48', 'description': None, 'user-visible': 'true', 'creator': None}}}, 'neighbors': None, 'last_modified': '00:00:07.263689'}
2021-02-24 06:22:56,991 - DEBUG - Route Targets: ['target:64512:8000039']
2021-02-24 06:22:56,991 - INFO - On all control nodes, Config, RI and RT verification for VN ctest-vn-45056538 passed
2021-02-24 06:22:56,991 - DEBUG - ====Verifying policy data for ctest-vn-45056538 in API_Server ======
2021-02-24 06:22:56,991 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:22:57,024 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:22:57,076 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:22:57,151 - DEBUG - Requesting: https://192.168.7.20:8082/virtual-network/4939ebe2-0290-4f2b-bc05-58e3a8f9b80d
2021-02-24 06:22:57,185 - DEBUG - ==>Verifying data for policy with id: 2ad1e605-c616-4d44-ac83-424f8cdbddd0, fqn: ['admin_domain', 'ctest-TestBasicPolicyIpv4v6-66950153', 'ctest-policy-allow-all-89240486']
2021-02-24 06:22:57,185 - INFO - VN ctest-vn-45056538 Policy verification: verify_vn_policy_in_api_server, status: True
2021-02-24 06:22:57,186 - DEBUG - Verifying the vn in opserver
2021-02-24 06:22:57,186 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538 virtual network link  through opserver 192.168.7.20
2021-02-24 06:22:57,186 - DEBUG - Requesting: https://192.168.7.20:8081/analytics/uves/virtual-networks
2021-02-24 06:22:58,853 - DEBUG - vn link and name as {'href': 'https://192.168.7.20:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538'}
2021-02-24 06:22:58,853 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538 virtual network link  through opserver 192.168.7.29
2021-02-24 06:22:58,854 - DEBUG - Requesting: https://192.168.7.29:8081/analytics/uves/virtual-networks
2021-02-24 06:22:59,015 - DEBUG - vn link and name as {'href': 'https://192.168.7.29:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538'}
2021-02-24 06:22:59,016 - DEBUG - Verifying the admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538 virtual network link  through opserver 192.168.7.34
2021-02-24 06:22:59,016 - DEBUG - Requesting: https://192.168.7.34:8081/analytics/uves/virtual-networks
2021-02-24 06:22:59,170 - DEBUG - vn link and name as {'href': 'https://192.168.7.34:8081/analytics/uves/virtual-network/admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538?flat', 'name': 'admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538'}
2021-02-24 06:22:59,170 - INFO - Validated that VN admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-45056538 is found in opserver
2021-02-24 06:22:59,400 - DEBUG - Do not have enough data to verify VN in agent
2021-02-24 06:22:59,512 - DEBUG - VRF ids for VN ctest-vn-45056538: {}
2021-02-24 06:22:59,963 - DEBUG - Services list from nova: [<Service: 1>, <Service: 3>, <Service: 4>, <Service: 16>]
2021-02-24 06:23:01,245 - INFO - VM ([<Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:23:03,061 - INFO - VM ([<Server: ctest-TestBasicPolicyIpv4v6-66950153-43609023>]) created on node: (nodec9), Zone: (nova:nodec9)
2021-02-24 06:23:03,062 - INFO - Waiting for VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 to be up..
2021-02-24 06:23:03,188 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:08,313 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:13,520 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:18,751 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:23,979 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:29,173 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is still in BUILD state, Expected: ACTIVE
2021-02-24 06:23:34,382 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-46016978> is in ACTIVE state now
2021-02-24 06:23:34,383 - INFO - VM name : ctest-TestBasicPolicyIpv4v6-66950153-46016978
2021-02-24 06:23:34,616 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 ID is 8e408ef9-5d3a-48f8-86fe-57c61e974979
2021-02-24 06:23:34,658 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 launched on Node nodec9.maas
2021-02-24 06:23:34,905 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/8e408ef9-5d3a-48f8-86fe-57c61e974979
2021-02-24 06:23:35,608 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/8e408ef9-5d3a-48f8-86fe-57c61e974979
2021-02-24 06:23:35,700 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine-interface/7e5bbd8f-0d80-4309-a1a6-90f205d527dc
2021-02-24 06:23:38,948 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 999ms')
2021-02-24 06:23:38,948 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:38,985 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:38,985 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:23:43,042 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1021ms')
2021-02-24 06:23:43,042 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:43,100 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:43,101 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:23:47,135 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1009ms')
2021-02-24 06:23:47,135 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:47,169 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:47,169 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:23:51,199 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1002ms')
2021-02-24 06:23:51,200 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:51,230 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:51,230 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:23:55,263 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1002ms')
2021-02-24 06:23:55,263 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:55,293 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:55,293 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:23:59,335 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1006ms')
2021-02-24 06:23:59,335 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:23:59,369 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:23:59,369 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:24:03,424 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1022ms')
2021-02-24 06:24:03,425 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:24:03,465 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:24:03,466 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:24:07,523 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1022ms')
2021-02-24 06:24:07,524 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:24:07,555 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:24:07,555 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:24:11,620 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 0 received, 100% packet loss, time 1032ms')
2021-02-24 06:24:11,620 - DEBUG - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed!
2021-02-24 06:24:11,661 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 151.220.74.193 and allocation pool is NOT set
2021-02-24 06:24:11,662 - DEBUG - Gateway for vn admin_domain:ctest-TestBasicPolicyIpv4v6-66950153:ctest-vn-26209205 is 37e7:853a:d18f:7e98:8cbc:9244:0:1 and allocation pool is NOT set
2021-02-24 06:24:15,714 - DEBUG - (True, 'PING 169.254.0.7 (169.254.0.7) 56(84) bytes of data.\r\n64 bytes from 169.254.0.7: icmp_seq=2 ttl=63 time=5.61 ms\r\n\r\n--- 169.254.0.7 ping statistics ---\r\n2 packets transmitted, 1 received, 50% packet loss, time 1018ms\r\nrtt min/avg/max/mdev = 5.610/5.610/5.610/0.000 ms')
2021-02-24 06:24:15,714 - INFO - Ping to Metadata IP 169.254.0.7 of VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 passed
2021-02-24 06:24:15,771 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:15,772 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:15,812 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:16,026 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:21,027 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:21,028 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:21,066 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:21,276 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:26,277 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:26,277 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:26,304 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:26,497 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:31,497 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:31,498 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:31,536 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:31,771 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:36,772 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:36,772 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:36,802 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:37,009 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:42,010 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:42,011 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:42,049 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:42,254 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:47,255 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:47,256 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:47,294 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:47,524 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:52,525 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:52,526 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:52,559 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:52,770 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:24:57,770 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:24:57,770 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:24:57,798 - DEBUG - Error on ssh to ubuntu@169.254.0.7:22, result: /bin/bash: connect: Connection refused
/bin/bash: /dev/tcp/169.254.0.7/22: Connection refused {'failed': True, 'command': '(echo > /dev/tcp/169.254.0.7/22)', 'real_command': '/bin/bash -l -c "(echo > /dev/tcp/169.254.0.7/22)"', 'return_code': 1, 'succeeded': False, 'stderr': ''}
2021-02-24 06:24:58,186 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is NOT ready for SSH connections, VM status: ACTIVE
2021-02-24 06:25:03,187 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:03,187 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-46016978, IP 151.220.74.195, Port 22
2021-02-24 06:25:03,335 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 is ready for SSH connections
2021-02-24 06:25:03,336 - INFO - Waiting for VM ctest-TestBasicPolicyIpv4v6-66950153-43609023 to be up..
2021-02-24 06:25:03,532 - DEBUG - VM <Server: ctest-TestBasicPolicyIpv4v6-66950153-43609023> is in ACTIVE state now
2021-02-24 06:25:03,532 - INFO - VM name : ctest-TestBasicPolicyIpv4v6-66950153-43609023
2021-02-24 06:25:03,740 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-43609023 ID is 6f8f7e07-e644-4e6b-bc79-8c7887a88e2e
2021-02-24 06:25:03,740 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-43609023 launched on Node nodec9.maas
2021-02-24 06:25:03,956 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine/6f8f7e07-e644-4e6b-bc79-8c7887a88e2e
2021-02-24 06:25:03,987 - DEBUG - Requesting: https://192.168.7.34:8082/virtual-machine-interface/962f1d35-a2ca-4087-89b4-9b2e09f907ed
2021-02-24 06:25:05,175 - DEBUG - (True, 'PING 169.254.0.8 (169.254.0.8) 56(84) bytes of data.\r\n64 bytes from 169.254.0.8: icmp_seq=1 ttl=63 time=6.43 ms\r\n64 bytes from 169.254.0.8: icmp_seq=2 ttl=63 time=5.46 ms\r\n\r\n--- 169.254.0.8 ping statistics ---\r\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\r\nrtt min/avg/max/mdev = 5.462/5.949/6.437/0.493 ms')
2021-02-24 06:25:05,175 - INFO - Ping to Metadata IP 169.254.0.8 of VM ctest-TestBasicPolicyIpv4v6-66950153-43609023 passed
2021-02-24 06:25:05,248 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:05,248 - DEBUG - Waiting to SSH to VM ctest-TestBasicPolicyIpv4v6-66950153-43609023, IP 66.84.199.195, Port 22
2021-02-24 06:25:05,372 - DEBUG - VM ctest-TestBasicPolicyIpv4v6-66950153-43609023 is ready for SSH connections
2021-02-24 06:25:05,372 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:05,373 - DEBUG - Running remote_cmd, Cmd : ping -s 56 -c 3 -W 1  66.84.199.195, host_string: ubuntu@169.254.0.7, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-24 06:25:05,374 - DEBUG - ping -s 56 -c 3 -W 1  66.84.199.195
2021-02-24 06:25:25,435 - DEBUG - PING 66.84.199.195 (66.84.199.195) 56(84) bytes of data.
64 bytes from 66.84.199.195: icmp_req=1 ttl=63 time=12.7 ms
64 bytes from 66.84.199.195: icmp_req=2 ttl=63 time=3.51 ms
64 bytes from 66.84.199.195: icmp_req=3 ttl=63 time=0.817 ms

--- 66.84.199.195 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2013ms
rtt min/avg/max/mdev = 0.817/5.694/12.751/5.110 ms
2021-02-24 06:25:25,436 - INFO - Ping to IP 66.84.199.195 from VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 passed
2021-02-24 06:25:25,559 - DEBUG - Policy Update Response {"network-policy": {"href": "https://192.168.7.34:8082/network-policy/2ad1e605-c616-4d44-ac83-424f8cdbddd0", "uuid": "2ad1e605-c616-4d44-ac83-424f8cdbddd0"}}
2021-02-24 06:25:25,559 - DEBUG - verify_vm_launched is skipped since self.vm_launch_flag is set
2021-02-24 06:25:25,560 - DEBUG - Running remote_cmd, Cmd : ping -s 56 -c 3 -W 1  66.84.199.195, host_string: ubuntu@169.254.0.7, password: ubuntugateway: root@192.168.7.9, gateway password: c0ntrail123
2021-02-24 06:25:25,560 - DEBUG - ping -s 56 -c 3 -W 1  66.84.199.195
2021-02-24 06:25:29,247 - DEBUG - PING 66.84.199.195 (66.84.199.195) 56(84) bytes of data.

--- 66.84.199.195 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2010ms
2021-02-24 06:25:29,247 - WARNING - Ping to IP 66.84.199.195 from VM ctest-TestBasicPolicyIpv4v6-66950153-46016978 failed
2021-02-24 06:25:29,248 - INFO - Deleting VM ctest-TestBasicPolicyIpv4v6-66950153-43609023
2021-02-24 06:25:29,620 - INFO - Deleting VM ctest-TestBasicPolicyIpv4v6-66950153-46016978
2021-02-24 06:25:30,584 - INFO - Deleted policy ctest-policy-allow-all-89240486
2021-02-24 06:25:30,584 - INFO - Deleting VN ctest-vn-45056538 
2021-02-24 06:25:30,692 - DEBUG - VN 4939ebe2-0290-4f2b-bc05-58e3a8f9b80d still in use: Unable to complete operation on network 4939ebe2-0290-4f2b-bc05-58e3a8f9b80d. There are one or more ports still in use on the network.
Neutron server returns request_ids: ['req-18086802-6427-49c2-8a45-02324ced39a0']
2021-02-24 06:25:30,692 - WARNING - Deleting VN ctest-vn-45056538 failed..Will retry
2021-02-24 06:25:33,001 - DEBUG - Response for deleting network ()
2021-02-24 06:25:33,001 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/e75052d5-dcb7-4617-8740-681de5033f12
2021-02-24 06:25:33,025 - DEBUG - Response Code: 404
2021-02-24 06:25:33,026 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:25:33,049 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:25:33,100 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:25:33,166 - INFO - Validated that VN ctest-vn-45056538 is not found in API Server
2021-02-24 06:25:33,288 - DEBUG - VN ctest-vn-45056538 is not present in Agent 192.168.7.19 
2021-02-24 06:25:33,400 - DEBUG - VN ctest-vn-45056538 is not present in Agent 192.168.7.9 
2021-02-24 06:25:33,400 - INFO - Validated that VN ctest-vn-45056538 is not in any agent
2021-02-24 06:25:33,973 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-vn-45056538 info
2021-02-24 06:25:33,973 - INFO - Deleting VN ctest-vn-26209205 
2021-02-24 06:25:34,369 - DEBUG - Response for deleting network ()
2021-02-24 06:25:34,369 - DEBUG - Requesting: https://192.168.7.20:8082/routing-instance/7b655cb5-7738-499b-9899-8e1f205edcee
2021-02-24 06:25:34,392 - DEBUG - Response Code: 404
2021-02-24 06:25:34,393 - DEBUG - Requesting: https://192.168.7.20:8082/domains
2021-02-24 06:25:34,409 - DEBUG - Requesting: https://192.168.7.20:8082/domain/f27c063f-c6c4-434f-a616-97e72e0043e5
2021-02-24 06:25:34,451 - DEBUG - Requesting: https://192.168.7.20:8082/project/5acb2f8a-134d-4ee0-923f-daa914c96c94
2021-02-24 06:25:34,508 - INFO - Validated that VN ctest-vn-26209205 is not found in API Server
2021-02-24 06:25:34,632 - DEBUG - VN ctest-vn-26209205 is not present in Agent 192.168.7.19 
2021-02-24 06:25:34,749 - DEBUG - VN ctest-vn-26209205 is not present in Agent 192.168.7.9 
2021-02-24 06:25:34,750 - INFO - Validated that VN ctest-vn-26209205 is not in any agent
2021-02-24 06:25:35,197 - INFO - Validated that Routing instances and Config db in Control-nodes does not have VN ctest-vn-26209205 info
2021-02-24 06:25:37,217 - DEBUG - No XMPP flaps were noticed during the test
2021-02-24 06:25:37,217 - INFO - END TEST : test_basic_policy_allow_deny : PASSED[0:02:53]
2021-02-24 06:25:37,217 - INFO - --------------------------------------------------------------------------------
2021-02-24 06:25:39,232 - INFO - Deleted project: ctest-TestBasicPolicyIpv4v6-66950153, ID : 5acb2f8a-134d-4ee0-923f-daa914c96c94 
