time: 2021-02-18 05:43:53.822943Z
tags: worker-0
test: setUpClass (serial_scripts.k8s_auth.test_policy_combo.TestPolicyCombo)
time: 2021-02-18 05:43:53.822943Z
failure: setUpClass (serial_scripts.k8s_auth.test_policy_combo.TestPolicyCombo) [ multipart
Content-Type: text/x-traceback;charset=utf8
traceback
1C5
Traceback (most recent call last):
  File "/contrail-test/serial_scripts/k8s_auth/test_policy_combo.py", line 22, in setUpClass
    super(TestPolicyCombo, cls).setUpClass()
  File "/contrail-test/serial_scripts/k8s_auth/base.py", line 14, in setUpClass
    dstdir='/var/tmp/templates')
  File "/contrail-test/common/contrail_test_init.py", line 1610, in copy_file_to_server
    host['username'] = self.host_data[ip]['username']
KeyError: '192.168.7.18'
0
]
tags: -worker-0
time: 2021-02-18 05:43:54.042880Z
tags: worker-0
test: setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResource)
time: 2021-02-18 05:43:54.042880Z
failure: setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResource) [ multipart
Content-Type: text/x-traceback;charset=utf8
traceback
1C1
Traceback (most recent call last):
  File "/contrail-test/serial_scripts/k8s_auth/test_resource.py", line 23, in setUpClass
    super(TestK8sResource, cls).setUpClass()
  File "/contrail-test/serial_scripts/k8s_auth/base.py", line 14, in setUpClass
    dstdir='/var/tmp/templates')
  File "/contrail-test/common/contrail_test_init.py", line 1610, in copy_file_to_server
    host['username'] = self.host_data[ip]['username']
KeyError: '192.168.7.18'
0
]
tags: -worker-0
time: 2021-02-18 05:43:54.233596Z
tags: worker-0
test: setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResourceCustom)
time: 2021-02-18 05:43:54.233596Z
failure: setUpClass (serial_scripts.k8s_auth.test_resource.TestK8sResourceCustom) [ multipart
Content-Type: text/x-traceback;charset=utf8
traceback
1C7
Traceback (most recent call last):
  File "/contrail-test/serial_scripts/k8s_auth/test_resource.py", line 74, in setUpClass
    super(TestK8sResourceCustom, cls).setUpClass()
  File "/contrail-test/serial_scripts/k8s_auth/base.py", line 14, in setUpClass
    dstdir='/var/tmp/templates')
  File "/contrail-test/common/contrail_test_init.py", line 1610, in copy_file_to_server
    host['username'] = self.host_data[ip]['username']
KeyError: '192.168.7.18'
0
]
tags: -worker-0
time: 2021-02-18 05:43:54.526919Z
tags: worker-0
test: setUpClass (serial_scripts.k8s_auth.test_restart.TestRestart)
time: 2021-02-18 05:43:54.526919Z
failure: setUpClass (serial_scripts.k8s_auth.test_restart.TestRestart) [ multipart
Content-Type: text/x-traceback;charset=utf8
traceback
1BC
Traceback (most recent call last):
  File "/contrail-test/serial_scripts/k8s_auth/test_restart.py", line 22, in setUpClass
    super(TestRestart, cls).setUpClass()
  File "/contrail-test/serial_scripts/k8s_auth/base.py", line 14, in setUpClass
    dstdir='/var/tmp/templates')
  File "/contrail-test/common/contrail_test_init.py", line 1610, in copy_file_to_server
    host['username'] = self.host_data[ip]['username']
KeyError: '192.168.7.18'
0
]
tags: -worker-0
time: 2021-02-18 05:43:54.916039Z
tags: worker-0
test: setUpClass (serial_scripts.k8s_auth.test_restart.TestRestartWithPodResource)
time: 2021-02-18 05:43:54.916039Z
failure: setUpClass (serial_scripts.k8s_auth.test_restart.TestRestartWithPodResource) [ multipart
Content-Type: text/x-traceback;charset=utf8
traceback
1CC
Traceback (most recent call last):
  File "/contrail-test/serial_scripts/k8s_auth/test_restart.py", line 130, in setUpClass
    super(TestRestartWithPodResource, cls).setUpClass()
  File "/contrail-test/serial_scripts/k8s_auth/base.py", line 14, in setUpClass
    dstdir='/var/tmp/templates')
  File "/contrail-test/common/contrail_test_init.py", line 1610, in copy_file_to_server
    host['username'] = self.host_data[ip]['username']
KeyError: '192.168.7.18'
0
]
tags: -worker-0
